/* Generated by npm run build. Version 0.4.5. */
'use strict';
var VENT = (() => {
const modules={"src/browser-entry.js":function(module,exports,require){
module.exports = {
  ...require("src/simulation.js"),
  ...require("src/presets.js"),
  ...require("src/contracts.js"),
  ...require("src/scenario.js"),
};

},
"src/simulation.js":function(module,exports,require){
// simulation.js — top-level simulator wiring clock + mechanics + vent + gas.
//
// Run loop:
//   1. clock.step(dt)
//   2. controller.step(state, dt, deliveredSinceBreathStart)
//   3. If phase is EXPIRATION, override boundary with PRESSURE = PEEP
//   4. mechanics.step(params, state, boundary, dt)
//   5. gas_exchange.step(gas, params, compartments, dt) — V/Q evolution
//   6. monitor records raw signals.

const { SimulationClock } = require("src/clock.js");
const { ThreeCompartmentMechanics } = require("src/mechanics.js");
const { VcAcController } = require("src/ventilator/vc_ac.js");
const { PcAcController } = require("src/ventilator/pc_ac.js");
const { BreathPhase } = require("src/ventilator/controller.js");
const {
  makeBoundaryPressure, makeInitialState,
} = require("src/contracts.js");
const {
  makeInitialGasState, stepGasState, mixedArterialPo2, shuntFraction,
  deadSpaceFraction,
} = require("src/gas_exchange.js");
const { analyzeAll } = require("src/metrics.js");

class Simulation {
  constructor({
    params, controller, dt = 0.001, fio2 = 0.4, trackGas = true,
    // v0.4.4: scenario-owned initial state. The phenotype (PatientParams)
    // does NOT own initialPEEP or initialRecruitmentState. The simulation
    // caller must supply them explicitly, or pass initializationHistory
    // from which the recruitment state can be derived.
    initialPEEP, initialRecruitmentState, initializationHistory,
  }) {
    this.params = params;
    this.controller = controller;
    this.clock = new SimulationClock(dt);

    // Resolve initialPEEP: prefer caller-supplied scenario value; fall
    // back to controller.settings.peep for tests that wire only one
    // side. We do NOT guess from the phenotype.
    let resolvedPEEP;
    if (typeof initialPEEP === 'number') {
      resolvedPEEP = initialPEEP;
    } else if (controller.settings && typeof controller.settings.peep === 'number') {
      resolvedPEEP = controller.settings.peep;
    } else {
      throw new Error(
        'Simulation: scenario must provide initialPEEP (or controller.settings.peep)');
    }

    // Resolve initial recruitment state.
    //   - If caller supplied initialRecruitmentState, use it.
    //   - If caller supplied initializationHistory, run the recovery
    //     protocol (FE march over the history) — not yet implemented for
    //     full physics, so we reject and ask the caller to provide
    //     initialRecruitmentState explicitly.
    //   - Otherwise, fail explicitly (no guessing).
    let resolvedRecState;
    if (initialRecruitmentState) {
      resolvedRecState = initialRecruitmentState;
    } else if (initializationHistory) {
      throw new Error(
        'Simulation: initializationHistory recovery is reserved for a future ' +
        'release; pass initialRecruitmentState explicitly.');
    } else {
      throw new Error(
        'Simulation: scenario must provide initialRecruitmentState ' +
        '(or initializationHistory). The phenotype does not own recruitment.');
    }

    this.state = makeInitialState(params, {
      initialPEEP: resolvedPEEP,
      initialRecruitmentState: resolvedRecState,
    });
    this.mechanics = new ThreeCompartmentMechanics();
    this.trace = [];
    this.deliveredSinceBreathStart = 0;
    this.peepOverrideActive = false;
    this.fio2 = fio2;
    this.trackGas = trackGas;
    this.gas = trackGas ? makeInitialGasState(params, fio2) : null;
  }

  setPEEP(_value) {
    // Reserved for future PEEP changes within a run.
  }

  runFor(seconds) {
    if (!Number.isFinite(seconds) || seconds < 0) throw new Error('Duration must be finite and non-negative');
    const target = this.state.t + seconds;
    const maxSteps = Math.ceil(seconds / this.clock.dt) + 2;
    if (maxSteps > 1000000) throw new Error('Run exceeds one million steps');
    let steps = 0;
    while (this.state.t < target) {
      if (++steps > maxSteps) throw new Error('Simulation stopped: time did not advance');
      const result = this.step();
      if (result.failed) {
        const error = new Error(`Simulation stopped: ${result.output.failureKind || 'STEP_FAILED'}`);
        error.diagnostics = result.output;
        throw error;
      }
    }
    return this.trace;
  }

  step() {
    const dt = this.clock.dt;

    // Snapshot mutable controller state so a rejected step is transactional.
    // Both shipped controllers own scalar fields plus a BreathTracker.
    const controllerSnapshot = { ...this.controller };
    const trackerSnapshot = { ...this.controller.tracker };
    const restoreController = () => {
      Object.assign(this.controller, controllerSnapshot);
      Object.assign(this.controller.tracker, trackerSnapshot);
    };
    // 1. controller produces boundary.
    let boundary = this.controller.step(this.state, dt, this.deliveredSinceBreathStart);

    // 2. EXPIRATION phase override: PEEP pressure clamp.
    if (this.controller.phase === BreathPhase.EXPIRATION) {
      boundary = makeBoundaryPressure({
        pressureCmH2O: this.controller.settings.peep,
        fio2: this.controller.settings.fio2,
      });
    }

    // 3. Advance mechanics with the final boundary.
    let result;
    try {
      result = this.mechanics.step(this.params, this.state, boundary, dt);
    } catch (error) {
      restoreController();
      throw error;
    }
    let { state, output } = result;

    // v0.4.3: STEP_FAILED contract.
    //
    // If the mechanical solve failed, do NOT commit the new state, do
    // NOT advance time, do NOT update gas exchange or downstream metrics.
    // Return the failure output as diagnostics so the caller can react
    // (retry with smaller dt, abort the breath, surface error).
    if (output.solverFailure) {
      restoreController();
      this.lastFailure = output;
      // Do not push to trace; do not commit state.
      return { state: this.state, output, boundary, failed: true };
    }

    // 4. Gas exchange (parallel to mechanics, no irreversible coupling).
    if (this.trackGas) {
      this.gas = stepGasState(this.gas, this.params, state.compartments, dt);
    }

    // 5. Track cumulative inspired volume since breath start.
    // We use NET volume change (ΔV), not cumulative FLOW — the latter
    // over-counts because passive recoil leaks some inflow back out
    // through the airway during inspiration. ΔV is what fills the lung
    // and what Vt means clinically.
    if (this.controller.phase === BreathPhase.INSPIRATION) {
      // Reset at start of a new breath (cycleTime just rolled over to 0).
      if (this.controller.cycleTime <= dt) {
        this.deliveredSinceBreathStart = 0;
        this.inspStartVolume = this.state.totalVolume;
      }
      // Net V change since breath start.
      this.deliveredSinceBreathStart = state.totalVolume - this.inspStartVolume;
    }

    // 6. Commit state, append trace.
    this.state = state;
    this.trace.push({
      t: state.t,
      phase: this.controller.phase,
      boundaryKind: boundary.kind,
      output,
    });
    return { state, output, boundary, failed: false };
  }

  // Per-breath metrics from the current trace. setPEEP = the controller's
  // set PEEP value (used to compute auto-PEEP).
  metrics() {
    const setPEEP = this.controller.settings ? this.controller.settings.peep : 0;
    return analyzeAll(this.trace, setPEEP);
  }

  // Gas exchange summary at current state.
  gasSummary() {
    if (!this.trackGas || !this.gas) return null;
    return {
      pao2: mixedArterialPo2(this.gas, this.params),
      shunt: shuntFraction(this.gas, this.params),
      deadSpace: deadSpaceFraction(this.gas, this.params),
      inspiredPo2: this.gas.inspiredPo2,
    };
  }
}

module.exports = { Simulation, VcAcController, PcAcController };

},
"src/clock.js":function(module,exports,require){
// clock.js — runtime SimulationClock matching clock.spec.ts.
// Deterministic fixed-step clock. Identical traces across repeated runs.

class SimulationClock {
  constructor(dt) {
    if (!(typeof dt === 'number' && Number.isFinite(dt) && dt > 0)) {
      throw new Error('dt must be > 0 finite number');
    }
    this._t = 0;
    this._steps = 0;
    this.dt = dt;
  }

  get t() { return this._t; }
  get steps() { return this._steps; }

  step() {
    this._t = Math.round((this._t + this.dt) * 1e12) / 1e12;
    this._steps += 1;
    return this._t;
  }

  reset() {
    this._t = 0;
    this._steps = 0;
  }

  // Run a closure for `seconds` real-time, capped by 1e9 steps as safety.
  runFor(seconds, fn) {
    if (typeof seconds !== 'number' || !(seconds > 0)) {
      throw new Error('seconds must be > 0 finite number');
    }
    const total = Math.ceil(seconds / this.dt);
    if (total > 1e9) throw new Error(`runFor too many steps: ${total}`);
    for (let i = 0; i < total; i++) fn(this.step(), this.dt);
  }
}

module.exports = { SimulationClock };

},
"src/mechanics.js":function(module,exports,require){
// mechanics.js — ThreeCompartmentMechanics implementing the DynamicMechanics
// interface from mechanics.spec.ts.
//
// v0.4.2: nonlinear finite-capacity exponential elastic law with implicit
// Newton-Raphson integration. Conservation is exact in the discrete update
// by construction (Q_i = (V_new - V_old) / dt, Q_central = Σ Q_i).
//
// Architecture:
//
//   Pvent --[Rcentral]-- Pbranch --[Ri, availability_i]--> x 3 compartments
//
// Per-compartment constitutive law (v0.4.2):
//
//   Vmax_i = availability_i * capacity_i
//   p_el_i = -K_i * ln(1 - V_i / Vmax_i)         for 0 ≤ V_i < Vmax_i
//   P_alv_i = AOP + p_el_i
//   G_i    = availability_i / R_i                branch conductance
//
// ODEs (continuous):
//
//   dV_i/dt = G_i * (Pbranch - P_alv_i)
//   Q_central = sum_i G_i * (Pbranch - P_alv_i)
//
// For FLOW boundary: Q_central = Q_requested (the boundary condition).
// For PRESSURE boundary: Pvent is imposed; Pbranch is implicit.
//
// Implicit-Euler residual (per active compartment):
//
//   F_i = V_i^{n+1} - V_i^n - dt * G_i * (Pbranch^{n+1} - AOP - p_el(V_i^{n+1})) = 0
//
// FLOW additional residual:
//   F_Q = sum_i (V_i^{n+1} - V_i^n) / dt - Q_req = 0
//
// PRESSURE additional residual (with Rc > 0):
//   F_C = (Pvent - Pbranch^{n+1}) / Rc - sum_i (V_i^{n+1} - V_i^n) / dt = 0
//
// Jacobian entries:
//
//   dF_i/dV_i = 1 + dt * G_i * dp_el/dV_i       (= 1 + dt * G_i / Ctan_i)
//   dF_i/dPbranch = -dt * G_i
//   dF_Q/dV_i = 1/dt
//   dC/dV_i = -1/dt    (PRESSURE only)
//   dC/dPbranch = -1/Rc   (PRESSURE only)
//
// This is a 4x4 dense system (3 active compartments + Pbranch).
//
// Conservation (exact by construction):
//
//   Q_i = (V_i_new - V_i_old) / dt
//   Q_central = sum_i Q_i
//   FLOW:    Q_central = Q_requested      to solver tolerance
//   PRESSURE: Pvent = Pbranch + Rc * Q_central   to solver tolerance
//
// Recruitment/mechanics coupling (predictor-corrector):
//   1. From state at t^n compute pdist_i^n, get r_i* (predictor).
//   2. Apply feasibility floor (no closing past V/(1-eps)/cap).
//   3. Solve implicit mechanics with r fixed.
//   4. Compute pdist_i^{n+1}, get r_i^{n+1} (corrector via trapezoidal avg).
//   5. Re-apply feasibility floor.
//   6. If |r_corrector - r_predictor| > r_tol, re-solve mechanics once.
//
// Limiting case Rcentral = 0:
//   Pbranch = Pvent exactly; solve each compartment independently.

const {
  availabilityFor,
  elasticPressure,
  elasticPressureAboveAOP,
  forwardElasticVolume,
  branchConductance,
  effectiveVolumeCapacity,
  dPressureDVolume,
  EPS_CAP,
} = require("src/compartments.js");

const {
  recruitmentRate,
  minimumFeasibleRecruitment,
  distendingPressure,
  clamp,
} = require("src/recruitment.js");

// Solver configuration.
const SOLVER_TOL_ABS = 1e-5;
const SOLVER_TOL_REL = 1e-8;
const SOLVER_MAX_ITER = 25;
const LINESEARCH_MAX = 25;
const DT_SUBDIV_LIMIT = 8;
const RECRUITMENT_TOL = 1e-6;

// v0.4.3: dimensionally scaled convergence.
//
// The raw residual mixes compartment volume equations (units: L) with
// the boundary equation (units: cmH2O). A Euclidean norm over mixed
// units is meaningless. We scale each component by a state-aware scale
// and use the infinity norm:
//
//   R̂_V_i = R_V_i / V_scale
//   R̂_P   = R_P   / P_scale
//   ‖R̂‖∞ = max(|R̂_V|, |R̂_P|)
//
// Convergence criterion: ‖R̂‖∞ < SOLVER_TOL_SCALED.
//
// V_scale must be tight enough to reject false fixed points. Using Vmax
// as V_scale gives a loose tolerance that allows implicit-Euler to
// "lock in" at any sub-equilibrium point. Using a smaller V_scale
// (e.g., max(V_scale, 0.01 L)) forces convergence toward the true
// step-to-step fixed point, not the false one.
const SOLVER_TOL_SCALED = 1e-3;
const V_SCALE_FLOOR = 0.01;   // characteristic V scale, never larger

// State-aware scales (per-step, recomputed from current state).
// V_scale is bounded by V_SCALE_FLOOR to ensure tight convergence.
function computeScales(activeComps, params, pBranchGuess) {
  let vmaxMin = Infinity;
  for (const { cp, cs } of activeComps) {
    const vmax = effectiveVolumeCapacity(cp, cs.recruitment);
    if (vmax > 0 && vmax < vmaxMin) vmaxMin = vmax;
  }
  if (!isFinite(vmaxMin)) vmaxMin = V_SCALE_FLOOR;
  // Use a tight V_scale: never larger than V_SCALE_FLOOR (0.01 L).
  // This makes the per-step residual tolerance a meaningful fraction of
  // a typical compartment's transient response.
  const V_scale = Math.min(vmaxMin, V_SCALE_FLOOR);
  // P_scale: order-of-magnitude of airway pressure. The boundary
  // residual has units cmH2O. Use max(|pBranch|, |AOP|, 1) as scale.
  const P_scale = Math.max(Math.abs(pBranchGuess),
                           Math.abs(params.airwayOpeningPressure),
                           1);
  return { V_scale, P_scale };
}

// v0.4.3 → v0.4.4: classify boundary feasibility with direction awareness.
//
// Given a failed Newton solve, determine whether the requested boundary
// is structurally infeasible (would require crossing finite-capacity
// domains or non-physical state) or whether the failure is a transient
// Newton nonconvergence that retry with smaller dt could fix.
//
// v0.4.4 direction-aware bounds:
//
//   Positive/inspiratory flow (Q_cmd > 0):
//     Q_cmd * dt <= sum_i(max(0, Vmax_i - V_i))
//     Use remaining available capacity.
//
//   Negative/expiratory flow (Q_cmd < 0):
//     |Q_cmd| * dt <= sum_i(max(0, V_i))
//     Use removable current gas volume (subject to lower-bound V >= 0).
//
// The constrained nonlinear solve remains authoritative; this is a
// necessary condition for fast-fail classification.
function classifyBoundaryFeasibility(activeComps, params, boundary, dt) {
  let capacityRemaining = 0;     // for inspiration: Vmax_i - V_i
  let removableVolume = 0;        // for expiration: V_i
  for (const { cp, cs } of activeComps) {
    const vmax = effectiveVolumeCapacity(cp, cs.recruitment);
    capacityRemaining += Math.max(0, (1 - EPS_CAP) * vmax - cs.volume);
    removableVolume += Math.max(0, cs.volume);
  }

  if (boundary.kind === 'FLOW') {
    const requestedDelta = boundary.flowLps * dt;
    if (requestedDelta >= 0) {
      // Inspiratory: positive flow into available capacity.
      if (requestedDelta > capacityRemaining + 1e-12) {
        return 'INFEASIBLE_BOUNDARY';
      }
    } else {
      // Expiratory: negative flow removes existing gas.
      const removalRequested = -requestedDelta;
      if (removalRequested > removableVolume + 1e-12) {
        return 'INFEASIBLE_BOUNDARY';
      }
    }
    return 'SOLVER_NONCONVERGENCE';
  }

  if (boundary.kind === 'PRESSURE') {
    // For PRESSURE boundary, the system may be infeasible if the
    // pressure is so high it would saturate all compartments in dt.
    // Without running the simulation, treat all pressure-boundary
    // failures as SOLVER_NONCONVERGENCE — the pressure boundary itself
    // is always feasible (just raises the question of how flow will
    // resolve internally).
    return 'SOLVER_NONCONVERGENCE';
  }
  return 'SOLVER_NONCONVERGENCE';
}

// Compute ‖R̂‖∞ given residual vector F and scales.
function scaledNorm(F, scales) {
  let maxR = 0;
  for (let i = 0; i < F.length - 1; i++) {
    const r = Math.abs(F[i]) / scales.V_scale;
    if (r > maxR) maxR = r;
  }
  // Last entry is the boundary (P) residual.
  const rP = Math.abs(F[F.length - 1]) / scales.P_scale;
  if (rP > maxR) maxR = rP;
  return maxR;
}

// --- Newton solver for one implicit step --------------------------------

// Solve a 4x4 dense linear system in-place: A * x = b.
// Returns null if A is singular.
function solve4x4(A, b) {
  const n = b.length;
  // Gaussian elimination with partial pivoting.
  const M = A.map((row, i) => [...row, b[i]]);
  for (let i = 0; i < n; i++) {
    let maxVal = Math.abs(M[i][i]);
    let maxRow = i;
    for (let k = i + 1; k < n; k++) {
      if (Math.abs(M[k][i]) > maxVal) { maxVal = Math.abs(M[k][i]); maxRow = k; }
    }
    if (maxVal < 1e-30) return null;
    if (maxRow !== i) { const tmp = M[i]; M[i] = M[maxRow]; M[maxRow] = tmp; }
    for (let k = i + 1; k < n; k++) {
      const factor = M[k][i] / M[i][i];
      for (let j = i; j < n + 1; j++) M[k][j] -= factor * M[i][j];
    }
  }
  const x = new Array(n);
  for (let i = n - 1; i >= 0; i--) {
    let sum = M[i][n];
    for (let j = i + 1; j < n; j++) sum -= M[i][j] * x[j];
    x[i] = sum / M[i][i];
  }
  return x;
}

// Construct the residual F and Jacobian J for the implicit step.
// Unknowns: [V_0, V_1, V_2, Pbranch]  (only active compartments).
// `state` is a length-4 array (V_old for each active compartment + 0).
//   Actually we use the index of active compartments; let activeCount ≤ 3.
//   For simplicity: we always have exactly 3 unknowns for the volumes
//   (with placeholder compartments contributing trivially), and 1 for Pbranch.
//   Total 4x4.
function buildSystem(activeComps, vOld, pBranchGuess, boundary, params, dt) {
  // activeComps: [{cp, cs, G, idx}], where idx is the original compartment index.
  const N = activeComps.length;
  const dim = N + 1;  // +1 for Pbranch
  const F = new Array(dim).fill(0);
  const J = Array.from({ length: dim }, () => new Array(dim).fill(0));

  const aop = params.airwayOpeningPressure;
  let sumQ = 0;

  for (let i = 0; i < N; i++) {
    const { cp, cs, G } = activeComps[i];
    // Closed compartment: V fixed at 0.
    if (G === 0 || effectiveVolumeCapacity(cp, cs.recruitment) <= 0) {
      F[i] = 0;  // V_new is 0
      J[i][i] = 1;
      continue;
    }
    // If V is currently at zero (or below floating-point residual from a
    // previous deflation) AND the trial flow would be non-positive
    // (Pbranch ≤ AOP), the compartment cannot supply outflow from an empty
    // volume — force V_new = 0 with no flow contribution. Otherwise, treat
    // the compartment as fully dynamic.
    // Threshold is relative to Vmax: 1 ppm of capacity. Anything below that
    // is "effectively zero" for purposes of mechanical flow.
    const FLOW_ZERO_FRAC = 1e-6;
    const vmax = effectiveVolumeCapacity(cp, cs.recruitment);
    const FLOW_ZERO_TOL = vmax > 0 ? vmax * FLOW_ZERO_FRAC : 1e-9;
    const vNew = Math.max(0, Math.min(vOld[i], vmax * (1 - 2 * EPS_CAP)));
    // Strict inequality: only lock when Pbranch is unambiguously below AOP.
    // When Pbranch = AOP, the direction is indeterminate and we should let
    // Newton resolve it.
    const flowDir = G * (pBranchGuess - aop);
    // Saturation: V is at the capacity ceiling AND the trial flow wants to
    // push V higher. Lock at V=Vmax with no Q contribution.
    const satLimit = vmax > 0 ? vmax * (1 - EPS_CAP) : 0;
    if (vmax > 0 && vNew >= satLimit - 1e-15 && flowDir > 0) {
      F[i] = 0 - cs.volume;  // V stays at Vmax (clamped to vNew)
      J[i][i] = 1;
      J[i][N] = 0;
      continue;
    }
    if (vNew < FLOW_ZERO_TOL && flowDir < 0) {
      // Empty compartment, no driving inflow. Lock at V=0, no Q contribution.
      F[i] = 0 - cs.volume;
      J[i][i] = 1;
      J[i][N] = 0;
      continue;
    }
    // Evaluate the elastic law at the trial V.
    let pEl;
    if (vNew < FLOW_ZERO_TOL) {
      // V near zero but flow is incoming. Use a small regularizing V to
      // avoid singularity in p_el. The actual V_new is allowed to grow.
      const vTiny = 1e-12;
      pEl = elasticPressureAboveAOP(vTiny, cp, cs.recruitment);
    } else {
      pEl = elasticPressureAboveAOP(vNew, cp, cs.recruitment);
    }
    // v0.4.3: analytic tangent dP_el/dV = K/(Vmax - V).
    // (For V→0 with vTiny regularization, dPressureDVolume is well-defined
    // at the regularized point.)
    const vForTangent = vNew < FLOW_ZERO_TOL ? 1e-12 : vNew;
    const dpdV = dPressureDVolume(vForTangent, cp, cs.recruitment);
    F[i] = vNew - cs.volume - dt * G * (pBranchGuess - aop - pEl);
    J[i][i] = 1 + dt * G * dpdV;
    J[i][N] = -dt * G;
    sumQ += (vNew - cs.volume) / dt;
  }

  // Last row: boundary condition.
  if (boundary.kind === 'FLOW') {
    // F_Q = sum_i (V_new - V_old) / dt - Q_requested = 0
    F[N] = sumQ - boundary.flowLps;
    for (let i = 0; i < N; i++) J[N][i] = 1 / dt;
    J[N][N] = 0;
  } else {
    // PRESSURE boundary with Rc > 0: F_C = (Pvent - Pbranch)/Rc - sum_i ΔV/dt
    const Rc = params.centralAirwayResistance;
    if (Rc > 0) {
      F[N] = (boundary.pressureCmH2O - pBranchGuess) / Rc - sumQ;
      for (let i = 0; i < N; i++) J[N][i] = -1 / dt;
      J[N][N] = -1 / Rc;
    } else {
      // Rc = 0: Pbranch is fixed at Pvent; no C residual needed.
      F[N] = pBranchGuess - boundary.pressureCmH2O;
      J[N][N] = 1;
    }
  }

  return { F, J };
}

// Enforce volume feasibility: 0 ≤ V_i < (1 - EPS_CAP) * Vmax_i.
function feasibleV(v, cp, cs) {
  const vmax = effectiveVolumeCapacity(cp, cs.recruitment);
  if (vmax <= 0) {
    return 0;  // Closed compartment must have V = 0.
  }
  const limit = (1 - EPS_CAP) * vmax;
  if (v < 0) return 0;
  if (v > limit) return limit;
  return v;
}

// One Newton step with backtracking line search.
// `vTrial` and `pBranch` are arrays of trial values (mutated in place).
// Returns { converged, residual, iterations, scaledResidual,
//           lineSearchHalvings, activeSetTransitions }.
function newtonStep(activeComps, vTrial, pBranch, boundary, params, dt) {
  const N = activeComps.length;
  let iter;
  let lastResidualNorm = Infinity;
  let initialNorm = Infinity;
  let initialScaled = Infinity;
  let lastScaled = Infinity;
  let converged = false;
  let totalHalvings = 0;
  // v0.4.3: count active-set transitions (compartment crossing 0 or
  // (1 - EPS_CAP) * Vmax during this Newton call).
  let activeSetTransitions = 0;
  // Track each compartment's "regime" by whether its V is at the floor
  // (≤ floorTol * Vmax) or at the cap (≥ (1 - EPS_CAP) * Vmax).
  function regime(vNew, cp, cs) {
    const vmax = effectiveVolumeCapacity(cp, cs.recruitment);
    if (vmax <= 0) return 'CLOSED';
    const floorTol = 1e-6 * vmax;
    if (vNew <= floorTol) return 'FLOOR';
    const constLimit = (1 - EPS_CAP) * vmax;
    if (vNew >= constLimit - 1e-15) return 'CAP';
    return 'INTERIOR';
  }
  const initialRegimes = activeComps.map((ac, i) =>
    regime(vTrial[i], ac.cp, ac.cs));

  // v0.4.3: compute scales once at the start (state is approximately
  // fixed during Newton iteration; per-iter recomputation would just
  // jitter the convergence test).
  const scales = computeScales(activeComps, params, pBranch[0]);

  for (iter = 0; iter < SOLVER_MAX_ITER; iter++) {
    const { F, J } = buildSystem(
      activeComps, vTrial, pBranch[0], boundary, params, dt);

    // Raw Euclidean norm (kept for diagnostic, not used for convergence).
    let norm = 0;
    for (let i = 0; i < F.length; i++) norm += F[i] * F[i];
    norm = Math.sqrt(norm);
    if (iter === 0) initialNorm = norm;
    lastResidualNorm = norm;

    // v0.4.3: scaled infinity norm is the convergence criterion.
    const scaled = scaledNorm(F, scales);
    if (iter === 0) initialScaled = scaled;
    lastScaled = scaled;

    if (scaled < SOLVER_TOL_SCALED ||
        scaled < SOLVER_TOL_REL * Math.max(initialScaled, 1e-12)) {
      converged = true;
      break;
    }

    // Solve J * dx = -F.
    const b = F.map(x => -x);
    const dx = solve4x4(J, b);
    if (!dx) {
      return { converged: false, residual: norm,
               scaledResidual: scaled, iterations: iter, substeps: 0,
               lineSearchHalvings: totalHalvings,
               activeSetTransitions };
    }

    // Line search with backtracking on the volume feasibility.
    let stepScale = 1.0;
    let stepAccepted = false;
    let lineIter;
    for (lineIter = 0; lineIter < LINESEARCH_MAX; lineIter++) {
      const newVTrial = vTrial.map((v, i) => feasibleV(
        v + stepScale * dx[i], activeComps[i].cp, activeComps[i].cs));
      // Reject if a volume that was 0 (closed comp) tries to move away from 0.
      let trialOK = true;
      for (let i = 0; i < N; i++) {
        const { cp, cs, G } = activeComps[i];
        if (G === 0) continue;  // closed compartment stays at 0
        const vmax = effectiveVolumeCapacity(cp, cs.recruitment);
        if (vmax > 0) {
          const constLimit = (1 - EPS_CAP) * vmax;
          if (newVTrial[i] >= constLimit - 1e-15) { trialOK = false; break; }
        }
      }
      if (!trialOK) {
        stepScale *= 0.5;
        totalHalvings++;
        continue;
      }
      const newPBranch = pBranch[0] + stepScale * dx[N];
      // Re-evaluate residual at the trial. Use SCALED norm for step
      // acceptance (dimensionally consistent).
      let newScaled = 0;
      let sumQ = 0;
      const trialF = new Array(N + 1);
      for (let i = 0; i < N; i++) {
        const { cp, cs, G } = activeComps[i];
        if (G === 0) { trialF[i] = 0; continue; }
        const vmax = effectiveVolumeCapacity(cp, cs.recruitment);
        const floorFrac = 1e-6;
        const floorTol = vmax > 0 ? vmax * floorFrac : 1e-9;
        // Lock branch: empty + non-positive flow
        if (newVTrial[i] <= floorTol && (newPBranch - params.airwayOpeningPressure) <= 0) {
          trialF[i] = 0;
          continue;
        }
        const pEl = elasticPressureAboveAOP(newVTrial[i], cp, cs.recruitment);
        const r = newVTrial[i] - cs.volume
                  - dt * G * (newPBranch - params.airwayOpeningPressure - pEl);
        trialF[i] = r;
        sumQ += (newVTrial[i] - cs.volume) / dt;
      }
      // Boundary residual.
      let boundaryRes = 0;
      if (boundary.kind === 'FLOW') {
        boundaryRes = sumQ - boundary.flowLps;
      } else if (params.centralAirwayResistance > 0) {
        boundaryRes = (boundary.pressureCmH2O - newPBranch)
                      / params.centralAirwayResistance - sumQ;
      } else {
        boundaryRes = newPBranch - boundary.pressureCmH2O;
      }
      trialF[N] = boundaryRes;
      newScaled = scaledNorm(trialF, scales);

      if (newScaled < lastScaled) {
        // Accept step.
        // Count active-set transitions: any compartment that changed
        // regime (CLOSED/FLOOR/INTERIOR/CAP) since the start of Newton.
        const newRegimes = activeComps.map((ac, i) =>
          regime(newVTrial[i], ac.cp, ac.cs));
        for (let i = 0; i < N; i++) {
          if (newRegimes[i] !== initialRegimes[i]) {
            activeSetTransitions++;
            initialRegimes[i] = newRegimes[i];
          }
        }
        for (let i = 0; i < N; i++) vTrial[i] = newVTrial[i];
        pBranch[0] = newPBranch;
        stepAccepted = true;
        break;
      }
      stepScale *= 0.5;
      totalHalvings++;
    }
    if (!stepAccepted) {
      // Could not reduce residual; abort.
      return { converged: false, residual: norm,
               scaledResidual: lastScaled, iterations: iter, substeps: 0,
               lineSearchHalvings: totalHalvings,
               activeSetTransitions };
    }
  }
  return { converged, residual: lastResidualNorm,
           scaledResidual: lastScaled, iterations: iter, substeps: 0,
           lineSearchHalvings: totalHalvings,
           activeSetTransitions };
}

// --- Driver: implicit step with dt subdivision -------------------------

function solveImplicitStep(params, state, boundary, dt, recruitmentSnapshot) {
  // activeComps: compartments that can conduct (availability > 0).
  const activeComps = [];
  for (let i = 0; i < params.compartments.length; i++) {
    const cp = params.compartments[i];
    const cs = state.compartments[i];
    const csWithR = { ...cs, recruitment: recruitmentSnapshot[i] };
    const a = availabilityFor(cp, recruitmentSnapshot[i]);
    const G = branchConductance(cp, recruitmentSnapshot[i]);
    if (a > 0 && G > 0) {
      activeComps.push({ cp, cs: csWithR, G, idx: i });
    }
  }
  // If no active compartments, the result is trivial (zero volume change).
  if (activeComps.length === 0) {
    const zero = state.compartments.map(cs => ({
      ...cs,
      volume: 0,
      flow: 0,
      alveolarPressure: params.airwayOpeningPressure,
    }));
    const totalVolume = zero.reduce((s, c) => s + c.volume, 0);
    const pVent = boundary.kind === 'PRESSURE'
      ? boundary.pressureCmH2O
      : params.airwayOpeningPressure;
    return {
      state: { ...state, compartments: zero, totalVolume, totalFlow: 0 },
      output: {
        airwayPressure: pVent,
        branchPressure: pVent,
        airwayFlow: 0,
        centralFlow: 0,
        deliveredVolume: totalVolume,
        totalVolume,
        compartmentVolumes: zero.map(c => c.volume),
        compartmentFlows: zero.map(c => c.flow),
        compartmentPressures: zero.map(c => c.alveolarPressure),
        iterations: 0,
        residualNorm: 0,
        substeps: 1,
      },
    };
  }

  const N = activeComps.length;
  // Initialize trial volumes at current state; Pbranch at boundary value
  // (or AOP if FLOW with no flow).
  const vTrial = activeComps.map(({ cp, cs }) => feasibleV(cs.volume, cp, cs));
  const pBranch = [boundary.kind === 'PRESSURE'
    ? boundary.pressureCmH2O
    : params.airwayOpeningPressure];

  const r = newtonStep(activeComps, vTrial, pBranch, boundary, params, dt);
  if (r.converged) {
    return finalize(activeComps, vTrial, pBranch[0], state, boundary, params, dt,
                    r.iterations, r.residual, r.scaledResidual, 1,
                    r.lineSearchHalvings, r.activeSetTransitions);
  }
  // Newton failed: try with halved dt.
  if (dt / 2 < 1e-6) {
    // Last resort: distinguish INFEASIBLE_BOUNDARY from SOLVER_NONCONVERGENCE.
    //
    // v0.4.3 contract:
    //   - INFEASIBLE_BOUNDARY: the requested flow/pressure would require
    //     crossing the finite-capacity domain. The Newton solver failed
    //     because the problem has no feasible solution, not because of
    //     iteration issues.
    //   - SOLVER_NONCONVERGENCE: the Newton iteration ran out of steps
    //     or its line search failed to reduce the residual, but the
    //     problem may still be feasible.
    //
    // We probe feasibility: given the current state, can the requested
    // boundary be satisfied without crossing any Vmax? If yes, the
    // failure is a SOLVER_NONCONVERGENCE; if no, INFEASIBLE_BOUNDARY.
    const classification = classifyBoundaryFeasibility(
      activeComps, params, boundary, dt);
    return {
      state: {
        t: state.t,
        compartments: state.compartments.map((cs, i) => ({
          ...cs,
          id: cs.id || params.compartments[i].id,
        })),
        airwayPressure: pBranch[0],
        totalFlow: 0,
        totalVolume: state.totalVolume,
      },
      output: {
        airwayPressure: pBranch[0],
        branchPressure: pBranch[0],
        airwayFlow: 0,
        centralFlow: 0,
        deliveredVolume: 0,
        totalVolume: state.totalVolume,
        compartmentVolumes: state.compartments.map(c => c.volume),
        compartmentFlows: state.compartments.map(() => 0),
        compartmentPressures: state.compartments.map(c => c.alveolarPressure),
        iterations: 0,
        residualNorm: r.residual,
        scaledResidual: r.scaledResidual,
        substeps: DT_SUBDIV_LIMIT,
        solverFailure: true,
        failureKind: classification,
      },
    };
  }
  const half1 = solveImplicitStep(params, state, boundary, dt / 2, recruitmentSnapshot);
  // Compute recruitment at the half-step state.
  const newR = half1.state.compartments.map((cs, i) =>
    recruitmentSnapshot[i]);  // unchanged; we re-solve from the same snapshot
  const half2 = solveImplicitStep(params, half1.state, boundary, dt / 2, newR);
  half2.output.substeps = 2;
  return half2;
}

function finalize(activeComps, vTrial, pBranchSolved, state, boundary,
                 params, dt, iterations, residualNorm, scaledResidual,
                 substeps, lineSearchHalvings, activeSetTransitions) {
  // Build new state.
  const aop = params.airwayOpeningPressure;
  const nextComps = state.compartments.map((cs, i) => {
    const ac = activeComps.find(a => a.idx === i);
    if (!ac) {
      return { ...cs, volume: 0, flow: 0, alveolarPressure: aop };
    }
    const vNew = vTrial[activeComps.indexOf(ac)];
    const pAlv = elasticPressure(vNew, ac.cp, ac.cs.recruitment, aop);
    const q = (vNew - ac.cs.volume) / dt;
    return { ...cs, volume: vNew, flow: q, alveolarPressure: pAlv };
  });

  // Q_central = sum of Q_i (exact by construction).
  const compartmentFlows = nextComps.map(c => c.flow);
  const qCentral = compartmentFlows.reduce((s, q) => s + q, 0);

  // For FLOW: Pvent = Pbranch + Q_central * Rc.
  // For PRESSURE: Pvent is the imposed boundary value.
  const Rc = params.centralAirwayResistance;
  let pVent;
  if (boundary.kind === 'PRESSURE') {
    pVent = boundary.pressureCmH2O;
  } else {
    pVent = pBranchSolved + qCentral * Rc;
  }

  const totalVolume = nextComps.reduce((s, c) => s + c.volume, 0);

  return {
    state: {
      t: state.t + dt,
      compartments: nextComps,
      airwayPressure: pVent,
      totalFlow: qCentral,
      totalVolume,
    },
    output: {
      airwayPressure: pVent,
      branchPressure: pBranchSolved,
      airwayFlow: qCentral,
      centralFlow: qCentral,
      deliveredVolume: totalVolume,
      totalVolume,
      compartmentVolumes: nextComps.map(c => c.volume),
      compartmentFlows,
      compartmentPressures: nextComps.map(c => c.alveolarPressure),
      iterations,
      residualNorm,
      scaledResidual,
      substeps,
      // v0.4.3: per-step solver work counters for instrumentation.
      solverStats: {
        newtonIters: iterations,
        substeps,
        lineSearchHalvings,
        activeSetTransitions,
        residualNorm,
        scaledResidual,
        converged: iterations > 0 && iterations < SOLVER_MAX_ITER,
      },
    },
  };
}

// --- Mechanics step with predictor-corrector recruitment ---------------

class ThreeCompartmentMechanics {
  step(params, state, boundary, dt) {
    if (!(dt > 0)) throw new Error('dt must be > 0');
    if (boundary.kind !== 'FLOW' && boundary.kind !== 'PRESSURE') {
      throw new Error(`unknown boundary kind ${boundary.kind}`);
    }

    const aop = params.airwayOpeningPressure;
    const compartments = state.compartments;

    // 1. Predictor: compute recruitment update at t^n using P_alv^n.
    const rPredict = compartments.map((cs, i) => {
      const cp = params.compartments[i];
      const pAlv = cs.alveolarPressure || aop;
      const pdist = distendingPressure(pAlv, aop);
      let rCand = clamp(cs.recruitment + recruitmentRate(cs.recruitment, pdist, cp) * dt,
                        0, 1);
      // Apply feasibility floor.
      const rFloor = minimumFeasibleRecruitment(cs.volume, cp);
      rCand = Math.max(rCand, rFloor);
      return rCand;
    });

    // 2. Solve mechanics with rPredict.
    const sol1 = solveImplicitStep(params, state, boundary, dt, rPredict);

    // 3. Corrector: recompute recruitment at t^{n+1} using P_alv^{n+1}.
    const rCorrect = sol1.state.compartments.map((cs, i) => {
      const cp = params.compartments[i];
      const pAlv = cs.alveolarPressure || aop;
      const pdist = distendingPressure(pAlv, aop);
      // Trapezoidal: average the rates at t^n and t^{n+1}.
      const rateOld = recruitmentRate(
        compartments[i].recruitment,
        distendingPressure(compartments[i].alveolarPressure || aop, aop),
        cp);
      const rateNew = recruitmentRate(
        cs.recruitment,
        pdist,
        cp);
      const rMid = clamp(
        compartments[i].recruitment + 0.5 * (rateOld + rateNew) * dt,
        0, 1);
      // Apply feasibility floor.
      const rFloor = minimumFeasibleRecruitment(cs.volume, cp);
      return Math.max(rMid, rFloor);
    });

    // 4. If corrector moved materially, re-solve once.
    let final = sol1;
    for (let i = 0; i < compartments.length; i++) {
      if (Math.abs(rCorrect[i] - rPredict[i]) > RECRUITMENT_TOL) {
        const newState = {
          ...state,
          compartments: state.compartments.map((cs, idx) => ({
            ...cs,
            recruitment: rCorrect[idx],
          })),
        };
        final = solveImplicitStep(params, newState, boundary, dt, rCorrect);
        break;
      }
    }

    // 5. Stamp the corrector recruitment into final state for next step.
    final.state.compartments = final.state.compartments.map((cs, i) => ({
      ...cs,
      recruitment: rCorrect[i],
    }));

    return final;
  }
}

module.exports = {
  ThreeCompartmentMechanics,
  EPS_CAP,
  SOLVER_TOL_ABS,        // raw tolerance (diagnostic only)
  SOLVER_TOL_SCALED,     // v0.4.3: dimensionlessly scaled convergence criterion
  SOLVER_TOL_REL,
  SOLVER_MAX_ITER,
  RECRUITMENT_TOL,
  solve4x4,
  buildSystem,
  newtonStep,
  solveImplicitStep,
  // Backward-compat shim: legacy tests called `solveBranchForFlow`. The
  // v0.4.2 solver is implicit; this returns the per-step solve output.
  solveBranchForFlow(boundary, params, compartments) {
    const m = new ThreeCompartmentMechanics();
    const state = {
      t: 0,
      compartments: compartments.map((cs, i) => ({
        id: params.compartments[i].id,
        volume: cs.volume,
        flow: 0,
        alveolarPressure: 0,
        recruitment: cs.recruitment ?? 1,
      })),
      airwayPressure: 0,
      totalFlow: 0,
      totalVolume: compartments.reduce((s, c) => s + c.volume, 0),
    };
    const rPredict = state.compartments.map(c => c.recruitment);
    const sol = solveImplicitStep(params, state, boundary, 0.001, rPredict);
    return {
      pBranch: sol.output.branchPressure,
      pVent: sol.output.airwayPressure,
      delivered: sol.output.centralFlow,
      requested: boundary.kind === 'FLOW' ? boundary.flowLps : null,
    };
  },
};

},
"src/compartments.js":function(module,exports,require){
// compartments.js — per-compartment elastic recoil law.
//
// Law (finite-capacity exponential, per V0.4.2_MATHEMATICAL_MODEL.md):
//   Vmax   = availability * capacity
//   p_el   = -K * ln(1 - V / Vmax)             for 0 ≤ V < Vmax
//   P_alv  = AOP + p_el
//
// Equivalent forward form (used by init and tests):
//   V(P)   = Vmax * [1 - exp(-(P - AOP) / K)]  for P ≥ AOP
//
// Existing preset convention is preserved:
//   capacity   -> Vcap_i_full   (asymptotic elastic volume when fully available)
//   elasticScale -> K_i        (exponential stiffening pressure scale, cmH2O)
//   derived    -> C_i_full = capacity / elasticScale  (tangent compliance at AOP)
//
// Branch conductance scales with availability:
//   G_i(a) = a / R_i_full    for a > 0, else G_i = 0.
//
// Rules (v0.4.2):
//   - Normal availability = 1.
//   - Recruitable availability = recruitment state r ∈ [0,1].
//   - Consolidated availability = 0 (carries perfusion only, no elastic volume).
//   - elasticPressure rejects V ≥ (1 - epsCap) * Vmax explicitly; no hard clip.
//   - No `MAX_PRESSURE`; the pressure diverges naturally as V → Vmax (as designed).
//   - No `1000 * capacity` clamp; the Newton solver enforces feasibility via line search.

const EPS_CAP = 1e-9;

function availabilityFor(cp, recruitment) {
  if (cp.id === 'normal') return 1.0;
  if (cp.id === 'recruitable') {
    if (typeof recruitment !== 'number' || !Number.isFinite(recruitment)) {
      throw new Error('recruitment must be finite number');
    }
    if (recruitment < 0) return 0;
    if (recruitment > 1) return 1;
    return recruitment;
  }
  if (cp.id === 'consolidated') return 0.0;
  throw new Error(`unknown compartment id ${cp.id}`);
}

function fullCompliance(cp) {
  if (!(cp.elasticScale > 0)) throw new Error('elasticScale must be > 0');
  return cp.capacity / cp.elasticScale;
}

function effectiveVolumeCapacity(cp, recruitment) {
  return availabilityFor(cp, recruitment) * cp.capacity;
}

// Pressure above AOP from elastic volume in [0, Vmax).
// Throws if V is outside the finite-capacity domain.
function elasticPressureAboveAOP(volume, cp, recruitment) {
  const vmax = effectiveVolumeCapacity(cp, recruitment);
  if (vmax <= 0) {
    if (Math.abs(volume) <= 1e-15) return 0;
    throw new Error('positive volume in unavailable compartment');
  }
  if (volume < 0) {
    throw new Error(`negative elastic volume: V=${volume}`);
  }
  if (volume >= (1 - EPS_CAP) * vmax) {
    throw new Error(`volume outside finite-capacity domain: V=${volume}, Vmax=${vmax}`);
  }
  return -cp.elasticScale * Math.log1p(-volume / vmax);
}

// Absolute alveolar pressure = AOP + distending elastic pressure.
function elasticPressure(volume, cp, recruitment, aop = 0) {
  if (typeof aop !== 'number' || !Number.isFinite(aop)) {
    throw new Error('aop must be finite number');
  }
  return aop + elasticPressureAboveAOP(volume, cp, recruitment);
}

// Tangent compliance Ctan = dV/dP. Falls toward zero as V → Vmax.
function tangentCompliance(volume, cp, recruitment) {
  const a = availabilityFor(cp, recruitment);
  if (a <= 0) return 0;
  const vmax = a * cp.capacity;
  if (volume < 0 || volume >= vmax) {
    throw new Error('volume outside finite-capacity domain');
  }
  return a * fullCompliance(cp) * (1 - volume / vmax);
}

// dP/dV = 1 / Ctan (used by Newton Jacobian).
function dPressureDVolume(volume, cp, recruitment) {
  const c = tangentCompliance(volume, cp, recruitment);
  if (!(c > 0)) throw new Error('non-positive tangent compliance');
  return 1 / c;
}

// Inverse: V(P, a, AOP). Used by pressure-consistent initialization.
function forwardElasticVolume(pressure, cp, recruitment, aop = 0) {
  const a = availabilityFor(cp, recruitment);
  if (a <= 0) return 0;
  if (pressure <= aop) return 0;
  const vmax = a * cp.capacity;
  const p = pressure - aop;
  return vmax * (1 - Math.exp(-p / cp.elasticScale));
}

// Branch conductance. Scales linearly with availability.
// At a = 0, conductance is exactly 0 (closed compartment cannot conduct gas).
function branchConductance(cp, recruitment) {
  const a = availabilityFor(cp, recruitment);
  if (a <= 0) return 0;
  if (!(cp.resistance > 0)) throw new Error('resistance must be > 0');
  return a / cp.resistance;
}

// Legacy effective-capacity helper. Now an alias of effectiveVolumeCapacity
// (the old `capacityMultiplier * capacity` semantic is subsumed by availability).
function effectiveCapacity(cp, recruitment) {
  return effectiveVolumeCapacity(cp, recruitment);
}

// Backward-compatible: clampVolume now rejects infeasible volumes rather than
// silently clipping. Used only by legacy code paths and tests.
function clampVolume(volume, cp, recruitment) {
  const vmax = effectiveVolumeCapacity(cp, recruitment);
  if (vmax <= 0) {
    if (Math.abs(volume) <= 1e-15) return 0;
    throw new Error('positive volume in unavailable compartment');
  }
  if (volume < 0) return 0;
  if (volume >= (1 - EPS_CAP) * vmax) {
    throw new Error('volume outside finite-capacity domain');
  }
  return volume;
}

module.exports = {
  EPS_CAP,
  availabilityFor,
  fullCompliance,
  effectiveVolumeCapacity,
  effectiveCapacity,
  elasticPressureAboveAOP,
  elasticPressure,
  tangentCompliance,
  dPressureDVolume,
  forwardElasticVolume,
  branchConductance,
  clampVolume,
};

},
"src/recruitment.js":function(module,exports,require){
// recruitment.js — stateful dynamic recruitment/derecruitment with hysteresis.
//
// v0.4.2 kinetics (bounded opening/closing, finite-capacity-feasible):
//
// Driver:  pdist = max(P_alv - AOP, 0)        pressure above AOP, clamped to ≥0
//
// Opening:  dr/dt =  k_open * (pdist - P_open) * (1 - r)   if pdist >  P_open
// Closing:  dr/dt = -k_close * (P_close - pdist) * r       if pdist <  P_close
// Dead-band: dr/dt = 0                                      otherwise
//
// Required:  P_close < P_open.
//
// The factors (1-r) and r make [0,1] invariant for ordinary steps without
// hard clipping.
//
// v0.4.3 derecruitment feasibility (projection rule):
//
//   A decrease in availability decreases Vmax. The model must never
//   silently destroy elastic gas volume by clipping V to the new capacity.
//   For a recruitable compartment, the minimum feasible r is:
//
//     r_min = V / ((1 - epsCap) * capacity)
//
//   v0.4.3 implements a projection rule:
//
//     1. Compute proposed derecruitment r_new = stepRecruitment(...).
//     2. Compute r_min = minimumFeasibleRecruitment(V, capacity).
//     3. If r_new < r_min, project r_new onto the feasible set:
//        - If V exceeds (1 - EPS_PROJ) * Vmax(r_new) at the proposed r,
//          limit r_new to the largest feasible r with margin
//          V <= (1 - EPS_PROJ) * Vmax(r_feasible).
//        - Otherwise, accept r_new.
//     4. The remaining "trapped gas" can only leave via modeled flow.
//        This rule preserves the invariant: V <= Vmax(r) at all times.
//
//   Projection margin: EPS_PROJ = 1e-6, applied at the
//   feasibility boundary so subsequent small pressure changes do not
//   immediately re-trigger the projection.
//
// fN_max (the v0.4 multiplicative capacity scaling) is deprecated; the
// new model uses linear availability scaling instead.

const EPS_CAP = 1e-9;
const EPS_PROJ = 1e-6;          // v0.4.3: projection margin

const OPEN_DEFAULT = 25;       // cmH2O above AOP
const CLOSE_DEFAULT = 10;      // cmH2O above AOP
const K_OPEN_DEFAULT = 0.02;   // 1/(cmH2O·s)
const K_CLOSE_DEFAULT = 0.05;  // 1/(cmH2O·s)

function distendingPressure(pAlv, aop) {
  return Math.max(0, pAlv - aop);
}

// Bounded opening/closing rate. Returns dr/dt in 1/s.
// Caller must enforce P_close < P_open; we throw here if not.
function recruitmentRate(recruitment, pDist, params = {}) {
  const Popen = params.P_open ?? OPEN_DEFAULT;
  const Pclose = params.P_close ?? CLOSE_DEFAULT;
  const kopen = params.k_open ?? K_OPEN_DEFAULT;
  const kclose = params.k_close ?? K_CLOSE_DEFAULT;
  if (!(Pclose < Popen)) {
    throw new Error(`P_close (${Pclose}) must be < P_open (${Popen})`);
  }
  const r = clamp(recruitment, 0, 1);
  if (pDist > Popen) return kopen * (pDist - Popen) * (1 - r);
  if (pDist < Pclose) return -kclose * (Pclose - pDist) * r;
  return 0;
}

// Forward-Euler step. Returns the new r in [0,1].
function stepRecruitment(recruitment, PAlv, dt, params = {}, aop = 0) {
  const pdist = distendingPressure(PAlv, aop);
  const rate = recruitmentRate(recruitment, pdist, params);
  return clamp(recruitment + rate * dt, 0, 1);
}

// Minimum feasible recruitment given an existing elastic volume.
// A closing update may not move below this floor.
// For non-recruitable compartments this returns the constant availability.
function minimumFeasibleRecruitment(volume, cp, epsCap = EPS_CAP) {
  if (cp.id !== 'recruitable') {
    // Normal: availability is 1; consolidated: 0.
    if (cp.id === 'normal') return 1;
    if (cp.id === 'consolidated') return 0;
    throw new Error(`unknown compartment id ${cp.id}`);
  }
  if (cp.capacity <= 0) return 0;
  return clamp(volume / ((1 - epsCap) * cp.capacity), 0, 1);
}

// v0.4.3: step with feasibility projection.
// r_candidate is the rate-based update; if it tries to close below
// the feasible floor, project it onto the feasible set with margin.
function stepRecruitmentWithFloor(recruitment, PAlv, dt, volume, cp, aop = 0) {
  const rCandidate = stepRecruitment(recruitment, PAlv, dt, cp, aop);
  const rFloor = minimumFeasibleRecruitment(volume, cp);
  if (rCandidate >= rFloor) return rCandidate;
  // Projection: find the largest r <= rFloor with V <= (1 - EPS_PROJ) * Vmax(r).
  // For a linear Vmax(r) = r * capacity, the constraint is:
  //   V <= (1 - EPS_PROJ) * r * capacity
  //   r >= V / ((1 - EPS_PROJ) * capacity)
  if (cp.id !== 'recruitable' || cp.capacity <= 0) {
    return rFloor;  // non-recruitable: structural.
  }
  const projectedR = volume / ((1 - EPS_PROJ) * cp.capacity);
  // The clamped value must not exceed rFloor (the closed-loop floor).
  // We return max(rCandidate, projectedR) which is the smallest of:
  //   - rCandidate (the requested update)
  //   - projectedR (the feasibility boundary)
  //   and we cap at 1 via the rFloor + stepRecruitment floor at r=1.
  return Math.max(rCandidate, Math.min(projectedR, 1));
}

function clamp(x, lo, hi) {
  if (x < lo) return lo;
  if (x > hi) return hi;
  return x;
}

module.exports = {
  EPS_CAP,
  OPEN_DEFAULT,
  CLOSE_DEFAULT,
  K_OPEN_DEFAULT,
  K_CLOSE_DEFAULT,
  distendingPressure,
  recruitmentRate,
  stepRecruitment,
  minimumFeasibleRecruitment,
  stepRecruitmentWithFloor,
  clamp,
  // Deprecated (v0.4): kept as a no-op shim for legacy callers. The new law
  // uses availability-based capacity scaling, not the old capMult * capacity.
  capacityMultiplier(recruitment, _fN_max) {
    if (typeof recruitment !== 'number') return 1;
    if (recruitment < 0) return 1;
    if (recruitment > 1) return 1;
    return 1;  // No scaling; the new law scales via availability instead.
  },
};

},
"src/ventilator/vc_ac.js":function(module,exports,require){
// ventilator/vc_ac.js — Volume-Control Assist/Control controller.
// Passive VCV with square inspiratory flow, optional inspiratory pause.
//
// Phase rules per spec/VENTILATOR_CONTRACT.md:
//   INSPIRATION: request FLOW at Q_insp, FiO2 delivered
//   PAUSE:        request zero flow with closed inspiratory boundary
//                 (MechanicsOutput.flow approaches zero while static pressure
//                 equilibrates)
//   EXPIRATION:   P_airway exposed to PEEP (handled by the simulator layer
//                 with a passive expiration boundary)

const { BreathTracker, BreathPhase } = require("src/ventilator/controller.js");
const { makeBoundaryFlow, makeBoundaryPressure } = require("src/contracts.js");

class VcAcController {
  /**
   * @param {object} settings  VcAcSettings from ventilator.spec.ts
   *   { fio2, peep, rr, vt, inspiratoryFlow, inspiratoryPause }
   */
  constructor(settings) {
    ['peep', 'rr', 'vt', 'fio2'].forEach(k => {
      if (typeof settings[k] !== 'number' || !Number.isFinite(settings[k])) {
        throw new Error(`VcAcSettings.${k} must be finite number`);
      }
    });
    if (!(settings.rr > 0)) throw new Error('rr must be > 0');
    if (!(settings.vt > 0)) throw new Error('vt must be > 0');
    if (settings.peep < 0) throw new Error('peep must be ≥ 0');
    if (settings.fio2 < 0 || settings.fio2 > 1) {
      throw new Error('fio2 must be in [0,1]');
    }
    if (!(settings.inspiratoryFlow > 0)) {
      throw new Error('inspiratoryFlow must be > 0');
    }
    if (settings.inspiratoryPause != null && settings.inspiratoryPause < 0) {
      throw new Error('inspiratoryPause must be ≥ 0');
    }
    this.settings = {
      fio2: settings.fio2,
      peep: settings.peep,
      rr: settings.rr,
      vt: settings.vt,
      inspiratoryFlow: settings.inspiratoryFlow,
      inspiratoryPause: settings.inspiratoryPause || 0,
    };
    this.ti = this.settings.vt / this.settings.inspiratoryFlow;
    if (!(this.ti > 0)) throw new Error('inspiration time must be > 0');
    if (this.ti + this.settings.inspiratoryPause >= 60 / this.settings.rr) {
      throw new Error('Inspiration plus pause must leave time for expiration');
    }
    this.tracker = new BreathTracker({
      rr: this.settings.rr,
      ti: this.ti,
      pause: this.settings.inspiratoryPause,
    });
    this.phaseTime = 0;
    this.cycleTime = 0;
    this.breathIndex = 0;
    this.lastBoundaryKind = null;
    this.deliveredThisBreath = 0;
  }

  get breath() { return this.breathIndex; }
  get phase() { return this.tracker.phaseFor(this.cycleTime); }

  /**
   * Advance the controller by dt and return the requested boundary.
   * Simulator passes deliveredVolume (mL since last breath start) so the
   * controller can switch inspiration → pause when target Vt is met.
   *
   * @param {object} state   PatientState
   * @param {number} dt      seconds
   * @param {number} deliveredSinceBreathStart   volume L since this breath's start
   */
  step(_state, dt, deliveredSinceBreathStart = 0) {
    if (!(dt > 0)) throw new Error('dt must be > 0');

    // Begin new breath when current one is complete.
    if (this.tracker.isBreathComplete(this.cycleTime)) {
      this.tracker.beginBreath();
      this.cycleTime = 0;
      this.phaseTime = 0;
      this.deliveredThisBreath = 0;
    }

    const phase = this.tracker.phaseFor(this.cycleTime);
    let boundary;

    if (phase === BreathPhase.INSPIRATION) {
      // Switch inspiration → pause when target Vt has been delivered.
      if (deliveredSinceBreathStart >= this.settings.vt) {
        // zero-flow, observe static pressure (use PAUSE-equivalent boundary)
        boundary = makeBoundaryFlow({ flowLps: 0, fio2: this.settings.fio2 });
        this.lastBoundaryKind = 'PAUSE_FROM_VT_TARGET';
      } else {
        boundary = makeBoundaryFlow({
          flowLps: this.settings.inspiratoryFlow,
          fio2: this.settings.fio2,
        });
        this.lastBoundaryKind = 'INSPIRATION';
      }
    } else if (phase === BreathPhase.PAUSE) {
      boundary = makeBoundaryFlow({ flowLps: 0, fio2: this.settings.fio2 });
      this.lastBoundaryKind = 'PAUSE';
    } else {
      // EXPIRATION: P_airway is set by simulator to PEEP; we hand off
      // responsibility to the simulator by requesting zero flow (the
      // simulator layer is responsible for clamping P_airway at PEEP).
      boundary = makeBoundaryFlow({ flowLps: 0, fio2: this.settings.fio2 });
      this.lastBoundaryKind = 'EXPIRATION';
    }

    this.phaseTime += dt;
    this.cycleTime += dt;
    return boundary;
  }
}

module.exports = { VcAcController };

},
"src/ventilator/controller.js":function(module,exports,require){
// ventilator/controller.js — common breath/phase accounting.
//
// A breath cycle:
//   EXPIRATION → INSPIRATION → PAUSE (optional) → EXPIRATION
// Breath period T_breath = 60 / RR seconds.
// Ti = Vt / Q_insp (target inspiratory time).
// Pause occupies remaining (T_breath - Ti) − Te.
//
// Quadratic solve: inspiratory flow Q is fixed by Vt and Ti; if Vt/Ti > flowLimit,
// the cycle is invalid (raised as InvalidState).

function sq(x) { return x * x; }

class BreathPhase {
  static EXPIRATION = 'EXPIRATION';
  static INSPIRATION = 'INSPIRATION';
  static PAUSE = 'PAUSE';
}

class BreathTracker {
  constructor({ rr, ti, pause, cycleTime = 0 }) {
    if (!(rr > 0)) throw new Error('rr must be > 0');
    this.rr = rr;
    this.ti = ti;
    this.pause = pause || 0;
    this.cycleTime = cycleTime;
    this.breathIndex = 0;
  }

  beginBreath() {
    this.cycleTime = 0;
    this.breathIndex += 1;
  }

  // Return phase for current cycleTime. ti is full inspiration length.
  phaseFor(cycleTime) {
    if (cycleTime < this.ti) return BreathPhase.INSPIRATION;
    if (cycleTime < this.ti + this.pause) return BreathPhase.PAUSE;
    return BreathPhase.EXPIRATION;
  }

  breathPeriod() { return 60 / this.rr; }

  // Total inspiration time including pause = ti + pause.
  isBreathComplete(cycleTime) {
    return cycleTime >= this.breathPeriod();
  }
}

module.exports = { BreathPhase, BreathTracker };

},
"src/contracts.js":function(module,exports,require){
// contracts.js — JS implementation matching the types in contracts.spec.ts.
// The .spec.ts file is the source-of-record; this file is the runtime surface.
//
// BoundaryCondition:
//   FLOW    -> ventilator pushes flow at the airway
//   PRESSURE -> ventilator sets the airway pressure target

const assertFinite = (v, name) => {
  if (typeof v !== 'number' || !Number.isFinite(v)) {
    throw new Error(`${name} must be finite number, got ${v}`);
  }
};

// v0.4.3: forward elastic law helper (used by pressure-consistent init).
// Defined locally so contracts.js doesn't depend on compartments.js — keeps
// the contract surface independent of the physics module. Equivalent to
// `forwardElasticVolume` in compartments.js.
function forwardElasticVolume(pressure, cp, availability, aop = 0) {
  if (availability <= 0) return 0;
  if (pressure <= aop) return 0;
  const vmax = availability * cp.capacity;
  const p = pressure - aop;
  return vmax * (1 - Math.exp(-p / cp.elasticScale));
}

function makeBoundaryFlow({ flowLps, fio2 }) {
  assertFinite(flowLps, 'flowLps');
  assertFinite(fio2, 'fio2');
  return Object.freeze({ kind: 'FLOW', flowLps, fio2 });
}

function makeBoundaryPressure({ pressureCmH2O, fio2 }) {
  assertFinite(pressureCmH2O, 'pressureCmH2O');
  assertFinite(fio2, 'fio2');
  return Object.freeze({ kind: 'PRESSURE', pressureCmH2O, fio2 });
}

// CompartmentParams
const COMPARTMENT_IDS = Object.freeze(['normal', 'recruitable', 'consolidated']);

function makeCompartmentParams(p) {
  if (!COMPARTMENT_IDS.includes(p.id)) throw new Error(`unknown compartment id ${p.id}`);
  ['fraction', 'resistance', 'capacity', 'elasticScale',
   'perfusionFraction', 'deadSpaceFraction'].forEach(k => {
    if (typeof p[k] !== 'number' || !Number.isFinite(p[k])) {
      throw new Error(`CompartmentParams.${k} must be finite number`);
    }
  });
  if (p.fraction < 0) throw new Error('fraction < 0');
  if (p.capacity < 0) throw new Error('capacity < 0');
  // v0.4: optional recruitment-tuning fields (hysteresis thresholds + rates).
  // Default to recruitment.js defaults if unspecified.
  const reco = p.recruitment || {};
  return Object.freeze({
    id: p.id, fraction: p.fraction, resistance: p.resistance,
    capacity: p.capacity, elasticScale: p.elasticScale,
    perfusionFraction: p.perfusionFraction,
    deadSpaceFraction: p.deadSpaceFraction,
    P_open: typeof reco.P_open === 'number' ? reco.P_open : undefined,
    P_close: typeof reco.P_close === 'number' ? reco.P_close : undefined,
    k_open: typeof reco.k_open === 'number' ? reco.k_open : undefined,
    k_close: typeof reco.k_close === 'number' ? reco.k_close : undefined,
    // v0.4.2: fN_max is deprecated; the new model uses linear availability
    // scaling. Accepted for schema-compat but ignored by the new law.
    fN_max: typeof reco.fN_max === 'number' ? reco.fN_max : undefined,
  });
}

function makeCompartmentState(s) {
  ['volume', 'flow', 'alveolarPressure', 'recruitment'].forEach(k => {
    if (typeof s[k] !== 'number' || !Number.isFinite(s[k])) {
      throw new Error(`CompartmentState.${k} must be finite number`);
    }
  });
  if (s.recruitment < 0 || s.recruitment > 1) {
    throw new Error(`recruitment out of [0,1]: ${s.recruitment}`);
  }
  return Object.freeze({
    volume: s.volume, flow: s.flow,
    alveolarPressure: s.alveolarPressure, recruitment: s.recruitment,
  });
}

function makePatientParams(p) {
  if (!Array.isArray(p.compartments) || p.compartments.length !== 3) {
    throw new Error('PatientParams.compartments must be array of 3');
  }
  const compartments = p.compartments.map(makeCompartmentParams);
  const totalFrac = compartments.reduce((s, c) => s + c.fraction, 0);
  if (Math.abs(totalFrac - 1) > 1e-9) {
    throw new Error(`compartment fractions must sum to 1, got ${totalFrac}`);
  }
  const totalPerf = compartments.reduce((s, c) => s + c.perfusionFraction, 0);
  if (Math.abs(totalPerf - 1) > 1e-9) {
    throw new Error(`compartment perfusions must sum to 1, got ${totalPerf}`);
  }
  if (typeof p.centralAirwayResistance !== 'number' ||
      !Number.isFinite(p.centralAirwayResistance)) {
    throw new Error('centralAirwayResistance must be finite number');
  }
  if (typeof p.airwayOpeningPressure !== 'number' ||
      !Number.isFinite(p.airwayOpeningPressure)) {
    throw new Error('airwayOpeningPressure must be finite number');
  }
  return Object.freeze({
    compartments,
    centralAirwayResistance: p.centralAirwayResistance,
    airwayOpeningPressure: p.airwayOpeningPressure,
  });
}

function cloneState(state) {
  return {
    t: state.t,
    compartments: state.compartments.map(s => ({ ...s })),
    airwayPressure: state.airwayPressure,
    totalFlow: state.totalFlow,
    totalVolume: state.totalVolume,
  };
}

// Pressure-consistent initialization (v0.4.3).
//
// The initializer MUST NOT invent recruitment. Presets must own either:
//   - initialPEEP + initialRecruitmentState, or
//   - initializationHistory (not implemented in v0.4.3).
//
// For each compartment, the initial volume and pressure follow the
// constitutive law:
//
//   Vmax_i  = availability_i * capacity_i
//   p_el_i  = -K_i * ln(1 - V_i / Vmax_i)   for 0 <= V_i < Vmax_i
//   P_alv_i = AOP + p_el_i
//
// Lower-bound regime (PEEP <= AOP or compartment closed):
//   - V_i = 0
//   - never permit negative volume
//   - P_alv_i = AOP (do not force P_alv = PEEP, that would require V < 0)
//
// Closed-compartment invariant (Vmax = 0):
//   - V_i = 0
//   - branch conductance = 0
//   - flow = 0
function makeInitialState(params, options = {}) {
  // v0.4.4: pressure-consistent initialization. The phenotype does NOT
  // own initialPEEP or initialRecruitmentState. The caller must supply both
  // via `options`. The initializer never guesses recruitment state.
  //
  // Acceptable caller-provided recruitment values:
  //   - { normal: 1, recruitable: r, consolidated: 0 } where 0 ≤ r ≤ 1
  //     is an explicitly justified value (not 0.37 / 0.5 by convention).
  //   - For tests that exercise the lower-bound regime, `recruitable: 0`
  //     is the explicit "closed/no-recruitment" state — that is a
  //     documented initial condition, not a guess.
  //
  // If the phenotype contains `params.initialRecruitmentState` (legacy
  // caller-side convenience), we honor it but only when the caller did
  // not also supply `options.initialRecruitmentState`. We do NOT default
  // to a closed state silently.

  function pickRecState() {
    if (options.initialRecruitmentState) return options.initialRecruitmentState;
    if (params.initialRecruitmentState &&
        typeof params.initialRecruitmentState === 'object') {
      return params.initialRecruitmentState;
    }
    // Fail explicitly — never silently guess.
    throw new Error(
      'makeInitialState: initialRecruitmentState is required (caller must ' +
      'pass it via options or as part of the phenotype contract).');
  }

  function pickPEEP() {
    if (typeof options.initialPEEP === 'number') return options.initialPEEP;
    if (typeof params.initialPEEP === 'number') return params.initialPEEP;
    return null;
  }

  const peep = pickPEEP();
  if (peep === null) {
    throw new Error(
      'makeInitialState: initialPEEP is required (caller or controller must ' +
      'provide it). The initializer does not guess initial PEEP.');
  }

  const aop = params.airwayOpeningPressure;
  const recState = pickRecState();

  // Determine per-compartment availability from preset-owned recruitment.
  function availabilityFor(cp) {
    // Validate all three preset values even if some compartments are
    // structurally closed (capacity=0). Preset values must be finite
    // numbers or undefined; otherwise reject explicitly.
    function validateNumeric(name, expected) {
      if (recState[name] === undefined) return;
      if (typeof recState[name] !== 'number' || !Number.isFinite(recState[name])) {
        throw new Error(
          `makeInitialState: initialRecruitmentState.${name} must be finite number, got ${recState[name]}`);
      }
      if (expected !== undefined && recState[name] !== expected) {
        throw new Error(
          `makeInitialState: initialRecruitmentState.${name} must be ${expected} (preset said ${recState[name]})`);
      }
    }

    if (cp.id === 'normal') {
      validateNumeric('normal', 1);
      return 1.0;
    }
    if (cp.id === 'consolidated') {
      validateNumeric('consolidated', 0);
      return 0.0;
    }
    if (cp.id === 'recruitable') {
      validateNumeric('recruitable', undefined);
      return Math.max(0, Math.min(1, recState.recruitable ?? 0));
    }
    throw new Error(`unknown compartment id: ${cp.id}`);
  }

  const compartments = params.compartments.map((cp) => {
    const a = availabilityFor(cp);
    const vmax = a * cp.capacity;

    let volume;
    if (vmax <= 0) {
      volume = 0;
    } else if (peep > aop) {
      volume = forwardElasticVolume(peep, { ...cp, capacity: vmax }, a, aop);
    } else {
      volume = 0;  // lower-bound regime
    }

    if (vmax <= 0 && Math.abs(volume) > 1e-15) {
      throw new Error(
        `initial volume ${volume} > 0 in closed compartment ${cp.id} (Vmax=0)`);
    }
    if (vmax > 0 && volume >= vmax) {
      throw new Error(
        `initial volume ${volume} exceeds capacity ${vmax} for ${cp.id}`);
    }
    if (volume < 0) {
      throw new Error(
        `initial volume ${volume} is negative for ${cp.id} ` +
        `(lower-bound regime violated)`);
    }

    const alveolarPressure = (a > 0 && peep > aop) ? peep : aop;

    return {
      id: cp.id,
      volume,
      flow: 0,
      alveolarPressure,
      recruitment: a,
    };
  });

  return {
    t: 0,
    compartments,
    airwayPressure: peep,
    totalFlow: 0,
    totalVolume: compartments.reduce((s, c) => s + c.volume, 0),
  };
}

function clamp01(x) {
  if (x < 0) return 0;
  if (x > 1) return 1;
  return x;
}

module.exports = {
  COMPARTMENT_IDS,
  makeBoundaryFlow,
  makeBoundaryPressure,
  makeCompartmentParams,
  makeCompartmentState,
  makePatientParams,
  makeInitialState,
  cloneState,
};

},
"src/ventilator/pc_ac.js":function(module,exports,require){
// ventilator/pc_ac.js — Pressure-Control Assist/Control controller.
//
// Square-wave airway-pressure target: hold Paw = PEEP for EXPIRATION,
// Paw = PEEP + pinsp for INSPIRATION, optional PAUSE at PEEP + pinsp.
// Same boundary contract as vc_ac.js — never duplicates mechanics.
//
// Required settings:
//   fio2, peep, rr, pinsp (inspiratory pressure above PEEP), inspiratoryTime
// Optional:
//   inspiratoryPause (s), default 0
//
// Boundary emission:
//   INSPIRATION: makeBoundaryPressure({pressureCmH2O: peep + pinsp, fio2})
//   PAUSE:       makeBoundaryPressure({pressureCmH2O: peep + pinsp, fio2})
//                (same target — pause is just a hold at the same pressure)
//   EXPIRATION:  zero flow; simulator layer sets Paw = PEEP.
//
// The controller does NOT measure or compute Vt — Vt emerges from the
// passive lung mechanics under the commanded pressure.

const { BreathTracker, BreathPhase } = require("src/ventilator/controller.js");
const {
  makeBoundaryPressure, makeBoundaryFlow,
} = require("src/contracts.js");

class PcAcController {
  constructor(settings) {
    ['peep', 'rr', 'fio2', 'pinsp', 'inspiratoryTime'].forEach(k => {
      if (typeof settings[k] !== 'number' || !Number.isFinite(settings[k])) {
        throw new Error(`PcAcSettings.${k} must be finite number`);
      }
    });
    if (!(settings.rr > 0)) throw new Error('rr must be > 0');
    if (!(settings.pinsp > 0)) throw new Error('pinsp must be > 0');
    if (!(settings.inspiratoryTime > 0)) {
      throw new Error('inspiratoryTime must be > 0');
    }
    if (settings.peep < 0) throw new Error('peep must be ≥ 0');
    if (settings.fio2 < 0 || settings.fio2 > 1) {
      throw new Error('fio2 must be in [0,1]');
    }
    if (settings.inspiratoryPause != null && settings.inspiratoryPause < 0) {
      throw new Error('inspiratoryPause must be ≥ 0');
    }
    // Validate that inspiratory time fits within breath period.
    const tiTotal = settings.inspiratoryTime + (settings.inspiratoryPause || 0);
    const tBreath = 60 / settings.rr;
    if (tiTotal >= tBreath) {
      throw new Error(
        `inspiratory time ${settings.inspiratoryTime.toFixed(3)} + pause ` +
        `${(settings.inspiratoryPause || 0).toFixed(3)} exceeds breath ` +
        `period ${tBreath.toFixed(3)} at RR=${settings.rr}`
      );
    }
    this.settings = {
      fio2: settings.fio2,
      peep: settings.peep,
      rr: settings.rr,
      pinsp: settings.pinsp,
      inspiratoryTime: settings.inspiratoryTime,
      inspiratoryPause: settings.inspiratoryPause || 0,
    };
    this.tracker = new BreathTracker({
      rr: this.settings.rr,
      ti: this.settings.inspiratoryTime,
      pause: this.settings.inspiratoryPause,
    });
    this.phaseTime = 0;
    this.cycleTime = 0;
    this.breathIndex = 0;
  }

  get breath() { return this.breathIndex; }
  get phase() { return this.tracker.phaseFor(this.cycleTime); }

  step(_state, dt, _deliveredSinceBreathStart = 0) {
    if (!(dt > 0)) throw new Error('dt must be > 0');

    if (this.tracker.isBreathComplete(this.cycleTime)) {
      this.tracker.beginBreath();
      this.cycleTime = 0;
      this.phaseTime = 0;
    }

    const phase = this.tracker.phaseFor(this.cycleTime);
    let boundary;

    if (phase === BreathPhase.INSPIRATION || phase === BreathPhase.PAUSE) {
      // Square-wave pressure target: PEEP + pinsp during both INSPIRATION
      // and PAUSE. The simulator layer handles Paw = PEEP during EXPIRATION.
      boundary = makeBoundaryPressure({
        pressureCmH2O: this.settings.peep + this.settings.pinsp,
        fio2: this.settings.fio2,
      });
    } else {
      // EXPIRATION: zero flow; simulator sets Paw = PEEP.
      boundary = makeBoundaryFlow({ flowLps: 0, fio2: this.settings.fio2 });
    }

    this.phaseTime += dt;
    this.cycleTime += dt;
    return boundary;
  }
}

module.exports = { PcAcController };

},
"src/gas_exchange.js":function(module,exports,require){
// gas_exchange.js — compartmental V/Q gas exchange state (foundation only).
//
// This module defines the data structures and pure functions needed for
// FiO2-dependent oxygenation, shunt/low-VQ behavior, dead space, CO2
// production/elimination. It does NOT couple irreversibly to the
// ventilator controller — gas exchange runs as a parallel state
// evolution alongside mechanics.
//
// State per compartment:
//   { volume, recruitment, va_ratio (V/Q), po2, pco2, spo2 }
//
// Conventions:
//   po2, pco2 in mmHg; spo2 in [0, 1].
//   va_ratio = ventilation (L/s) / perfusion (L/s), normalized by the
//   compartment's perfusion fraction.
//   shunt_equivalent = 1 / (1 + va_ratio)  — high va_ratio → no shunt,
//   low va_ratio → high shunt effect.
//
// Functions:
//   makeInitialGasState(params)        — initial gas state for trace.
//   stepGasState(gas, params, comp, dt) — one step of gas evolution.
//   mixedArterialPo2(gas, params)      — perfusion-weighted PaO2.
//   shuntFraction(gas, params)         — perfusion-weighted shunt.
//
// The numerical values in the evolution are educational approximations,
// NOT validated physiology. See REVIEW_NOTES.md.

const ATMOSPHERIC_PO2 = 150;     // mmHg (FiO2=0.21 at sea level)
const HEMOGLOBIN_P50 = 26.7;     // mmHg
const HILL_N = 2.7;
const CO2_PRODUCTION_ML_PER_KG_MIN = 3.0;   // mL/kg/min (educational)
const REFERENCE_BODY_WEIGHT_KG = 70;
const STANDARD_CO2_PRODUCTION = CO2_PRODUCTION_ML_PER_KG_MIN * REFERENCE_BODY_WEIGHT_KG / 60; // mL/s

function makeInitialGasState(params, fio2 = 0.21) {
  const inspiredPo2 = (fio2 * (ATMOSPHERIC_PO2 - 47)) + 47; // simplified alveolar gas eq
  const gas = {
    fio2,
    inspiredPo2,
    compartments: params.compartments.map(c => ({
      va_ratio: c.fraction > 0 ? c.fraction / Math.max(c.perfusionFraction, 1e-6) : 0,
      po2: inspiredPo2,
      pco2: 40,
      spo2: 0.97,
    })),
  };
  return gas;
}

// Hill equation: SpO2 from PO2 (educational approximation).
function spo2FromPo2(po2) {
  if (po2 <= 0) return 0;
  const ratio = po2 / HEMOGLOBIN_P50;
  const spo2 = Math.pow(ratio, HILL_N) / (1 + Math.pow(ratio, HILL_N));
  return Math.max(0, Math.min(1, spo2));
}

function stepGasState(gas, params, compartments, dt) {
  // Simple time-evolution: each compartment's PO2 relaxes toward a
  // ventilation-perfusion-determined equilibrium. No coupling across
  // compartments at this stage — left as a P5+ extension hook.
  const next = {
    fio2: gas.fio2,
    inspiredPo2: gas.inspiredPo2,
    compartments: gas.compartments.map((g, i) => {
      const cp = params.compartments[i];
      const cs = compartments[i];
      // Ventilation proxy: |flow|, perfusion from params.
      const va_proxy = Math.abs(cs.flow) + 1e-6;
      const q_proxy = Math.max(cp.perfusionFraction, 1e-6);
      const va_ratio = va_proxy / q_proxy;
      // Alveolar PO2 equilibrium: weighted blend of inspired PO2 and
      // mixed-venous PO2 (40 mmHg) by va_ratio.
      const mixedVenousPo2 = 40;
      const alvPo2 = (gas.inspiredPo2 * va_ratio + mixedVenousPo2) / (va_ratio + 1);
      // Relaxation toward equilibrium (educational time constant).
      const tau = 4.0; // seconds
      const alpha = 1 - Math.exp(-dt / tau);
      const po2 = g.po2 + alpha * (alvPo2 - g.po2);
      // PCO2: inversely proportional to va_ratio, baseline 40 mmHg.
      const pco2 = 40 / Math.max(va_ratio, 0.01);
      return {
        va_ratio,
        po2,
        pco2: Math.max(pco2, 5),
        spo2: spo2FromPo2(po2),
      };
    }),
  };
  return next;
}

function mixedArterialPo2(gas, params) {
  // Perfusion-weighted PaO2 across compartments.
  let totalPerf = 0, weighted = 0;
  for (let i = 0; i < gas.compartments.length; i++) {
    const cp = params.compartments[i];
    const perf = cp.perfusionFraction;
    weighted += gas.compartments[i].po2 * perf;
    totalPerf += perf;
  }
  return totalPerf > 0 ? weighted / totalPerf : 0;
}

function shuntFraction(gas, params) {
  // Perfusion-weighted shunt = sum(perf * 1/(1+va_ratio)).
  let totalPerf = 0, weighted = 0;
  for (let i = 0; i < gas.compartments.length; i++) {
    const cp = params.compartments[i];
    const perf = cp.perfusionFraction;
    const va = gas.compartments[i].va_ratio;
    weighted += perf * (1 / (1 + va));
    totalPerf += perf;
  }
  return totalPerf > 0 ? weighted / totalPerf : 0;
}

function deadSpaceFraction(gas, params) {
  // V/Q ratio > 1 → dead space proxy. Perfusion-weighted dead-space.
  let totalPerf = 0, weighted = 0;
  for (let i = 0; i < gas.compartments.length; i++) {
    const cp = params.compartments[i];
    const perf = cp.perfusionFraction;
    const va = gas.compartments[i].va_ratio;
    weighted += perf * Math.max(0, (va - 1) / va);
    totalPerf += perf;
  }
  return totalPerf > 0 ? weighted / totalPerf : 0;
}

module.exports = {
  makeInitialGasState,
  stepGasState,
  mixedArterialPo2,
  shuntFraction,
  deadSpaceFraction,
  spo2FromPo2,
};

},
"src/metrics.js":function(module,exports,require){
// metrics.js — breath metrics analyzer.
//
// Independent of any controller: walks a Simulation.trace and emits one
// metrics record per completed breath. Metrics are derived from the
// waveform/state data, never copied from controller settings.
//
// Definition of phases (matches controller/VENTILATOR_CONTRACT.md):
//   EXPIRATION → INSPIRATION → PAUSE → EXPIRATION
// A "completed breath" is the segment between two consecutive
// EXPIRATION→INSPIRATION transitions.
//
// Measurement windows:
//   - PEEP:        median(Paw) over last 200 ms of the EXPIRATION phase
//                  before the next INSPIRATION.
//   - Ppeak:       max(Paw) during the INSPIRATION phase.
//   - Pplat:       median(Paw) over the late PAUSE phase (after the
//                  initial Paw equilibration), with flow |Q| < 0.05 L/s.
//                  "Late" = the second half of the PAUSE rows.
//   - driving ΔP:  Pplat − PEEP.
//   - Vt (inspired): end-inspiratory totalVolume − start-inspiratory totalVolume.
//   - Vt (expired): start-inspiratory totalVolume (breath n+1) −
//                   end-expiratory totalVolume (breath n). Falls back
//                   to the minimum totalVolume during EXPIRATION if the
//                   next breath hasn't started.
//   - Volume error: inspired Vt − expired Vt.
//   - RR:          1 / breath duration (s), reported as breaths/min.
//   - MV:          RR × Vt (L/min).
//   - Ti, Te:      phase durations, I:E = Ti/Te.
//   - Qpeak insp:  max(Q_airway) during INSPIRATION.
//   - Qpeak exp:   max(|Q_airway|) during EXPIRATION (peak expiratory flow).
//   - auto-PEEP:   if end-expiratory Paw is materially > set PEEP, the
//                  excess is reported as intrinsic PEEP (cmH2O). Zero
//                  when the model has fully equilibrated.
//   - compartment volumes and flows: end-inspiratory and end-expiratory
//                  per-compartment values from the trace.

const PLATEAU_FLOW_THRESHOLD = 0.05;     // L/s — flows below this count as static
const PEEP_WINDOW_MS = 200;              // last 200 ms of EXPIRATION
const PLATEAU_LATE_FRACTION = 0.5;       // second half of PAUSE rows

function phaseSegments(trace) {
  // Returns array of {phase, startIdx, endIdx} for each contiguous phase.
  const out = [];
  if (!trace || trace.length === 0) return out;
  let cur = { phase: trace[0].phase, startIdx: 0 };
  for (let i = 1; i < trace.length; i++) {
    if (trace[i].phase !== cur.phase) {
      cur.endIdx = i - 1;
      out.push(cur);
      cur = { phase: trace[i].phase, startIdx: i };
    }
  }
  cur.endIdx = trace.length - 1;
  out.push(cur);
  return out;
}

function median(arr) {
  if (arr.length === 0) return 0;
  const sorted = arr.slice().sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  if (sorted.length % 2) return sorted[mid];
  return (sorted[mid - 1] + sorted[mid]) / 2;
}

function maxAbs(arr) {
  if (arr.length === 0) return 0;
  let m = 0;
  for (const x of arr) {
    const a = Math.abs(x);
    if (a > m) m = a;
  }
  return m;
}

function analyzeBreath(trace, breathStartIdx, breathEndIdx) {
  // breathStartIdx: index of first EXPIRATION row (or 0 if first breath)
  // breathEndIdx:   index of the last row of the same breath
  const segs = phaseSegments(trace.slice(breathStartIdx, breathEndIdx + 1))
    .map(s => ({
      phase: s.phase,
      startIdx: s.startIdx + breathStartIdx,
      endIdx: s.endIdx + breathStartIdx,
    }));
  const insp = segs.find(s => s.phase === 'INSPIRATION');
  const pause = segs.find(s => s.phase === 'PAUSE');
  const expir = segs.find(s => s.phase === 'EXPIRATION');

  const rows = (s) => {
    if (!s) return [];
    return trace.slice(s.startIdx, s.endIdx + 1);
  };

  const inspRows = rows(insp);
  const pauseRows = rows(pause);
  const expirRows = rows(expir);

  // Ti = INSPIRATION duration; Te = EXPIRATION duration; pause adds to Ti
  // (typical convention: Ti = insp + pause, Te = expir).
  const Ti = insp && pause
    ? (trace[pause.endIdx].t - trace[insp.startIdx].t)
    : insp
      ? (trace[insp.endIdx].t - trace[insp.startIdx].t)
      : 0;
  const Te = expir ? (trace[expir.endIdx].t - trace[expir.startIdx].t) : 0;
  const breathDuration = Ti + Te;
  const RR = breathDuration > 0 ? 60 / breathDuration : 0;

  // Vt inspired = V at end of last phase before EXPIRATION - V at start of INSPIRATION
  let VtInspired = 0;
  if (insp) {
    const lastPhase = pause || insp;
    const vStart = trace[insp.startIdx].output.totalVolume;
    const vEnd = trace[lastPhase.endIdx].output.totalVolume;
    VtInspired = vEnd - vStart;
  }

  // Ppeak during INSPIRATION
  const pawsInsp = inspRows.map(r => r.output.airwayPressure);
  const Ppeak = pawsInsp.length ? Math.max(...pawsInsp) : 0;

  // Pplat: median Paw over the LATE half of PAUSE rows with |Q| below threshold.
  // If PAUSE is short or absent, fall back to the last INSPIRATION row's Paw
  // (which equals the static plateau when the controller has switched to
  // zero-flow after Vt target).
  let Pplat = 0;
  if (pauseRows.length > 0) {
    const start = Math.floor(pauseRows.length * PLATEAU_LATE_FRACTION);
    const late = pauseRows.slice(start);
    const staticLate = late.filter(r => Math.abs(r.output.airwayFlow) < PLATEAU_FLOW_THRESHOLD);
    const pool = staticLate.length > 0 ? staticLate : late;
    Pplat = median(pool.map(r => r.output.airwayPressure));
  } else if (inspRows.length > 0) {
    // No dedicated PAUSE phase — plateau is the equilibrated Paw at end
    // of inspiration (controller switched to zero-flow at Vt target).
    const tail = inspRows.slice(-Math.max(20, Math.floor(inspRows.length * 0.2)));
    Pplat = median(tail.map(r => r.output.airwayPressure));
  }

  // PEEP: median Paw over last 200 ms of EXPIRATION
  let PEEP = 0;
  if (expirRows.length > 0) {
    const lastT = trace[expir.endIdx].t;
    const cutoff = lastT - PEEP_WINDOW_MS / 1000;
    const window = expirRows.filter(r => r.t >= cutoff);
    const pool = window.length > 0 ? window : expirRows.slice(-10);
    PEEP = median(pool.map(r => r.output.airwayPressure));
  }

  const drivingPressure = Pplat - PEEP;

  // Peak inspiratory and expiratory flows
  const QpeakInsp = inspRows.length ? maxAbs(inspRows.map(r => r.output.airwayFlow)) : 0;
  const QpeakExp = expirRows.length ? maxAbs(expirRows.map(r => r.output.airwayFlow)) : 0;

  // Vt expired: minimum totalVolume during EXPIRATION, measured from
  // the start of inspiration (peak after a fully equilibrated breath)
  // to the trough of expiration.
  let VtExpired = 0;
  if (expirRows.length > 0 && insp) {
    const vPeak = trace[insp.endIdx].output.totalVolume; // approximate peak
    const vMin = Math.min(...expirRows.map(r => r.output.totalVolume));
    VtExpired = vPeak - vMin;
  }

  const volumeError = VtInspired - VtExpired;
  const MV = (RR * VtInspired) / 60 * 60; // L/min  (RR in /min × Vt in L)
  // auto-PEEP = (PEEP measured - PEEP set). Caller passes set PEEP.
  const autoPEEP = 0; // computed by caller from set vs measured

  // Compartment end-inspiratory / end-expiratory values
  const compartments = {};
  if (insp) {
    const cs = trace[pause ? pause.endIdx : insp.endIdx].output;
    for (let i = 0; i < (cs.compartmentVolumes || []).length; i++) {
      compartments[`comp_${i}`] = {
        endInspV: cs.compartmentVolumes[i],
        endInspF: (cs.compartmentFlows || [])[i],
        endInspP: (cs.compartmentPressures || [])[i],
      };
    }
  }
  if (expir) {
    const cs = trace[expir.endIdx].output;
    for (let i = 0; i < (cs.compartmentVolumes || []).length; i++) {
      const key = `comp_${i}`;
      if (!compartments[key]) compartments[key] = {};
      compartments[key].endExpV = cs.compartmentVolumes[i];
      compartments[key].endExpF = (cs.compartmentFlows || [])[i];
      compartments[key].endExpP = (cs.compartmentPressures || [])[i];
    }
  }

  return {
    Ti,
    Te,
    breathDuration,
    RR,
    MV,
    PEEP,
    Ppeak,
    Pplat,
    drivingPressure,
    VtInspired,
    VtExpired,
    volumeError,
    QpeakInsp,
    QpeakExp,
    autoPEEP,
    compartments,
  };
}

function analyzeAll(trace, setPEEP) {
  // Walk the trace and emit one metrics record per completed breath.
  // First breath starts at index 0. Each breath ends at the last row
  // before the next EXPIRATION→INSPIRATION transition (or end of trace).
  const metrics = [];
  const segments = phaseSegments(trace);
  // Find EXPIRATION starts (each is a breath boundary). The first breath
  // begins at trace start.
  const expirStarts = [0, ...segments
    .filter((s, i) => i > 0 && s.phase === 'EXPIRATION')
    .map(s => s.startIdx)];
  for (let i = 0; i < expirStarts.length; i++) {
    const startIdx = expirStarts[i];
    const endIdx = (i + 1 < expirStarts.length) ? expirStarts[i + 1] - 1 : trace.length - 1;
    if (endIdx <= startIdx) continue;
    const m = analyzeBreath(trace, startIdx, endIdx);
    m.breathIndex = i;
    m.breathStartT = trace[startIdx].t;
    m.breathEndT = trace[endIdx].t;
    m.autoPEEP = m.PEEP - (setPEEP || 0);
    metrics.push(m);
  }
  return metrics;
}

module.exports = { analyzeAll, analyzeBreath, phaseSegments };

},
"src/presets.js":function(module,exports,require){
// presets.js — Four mechanical-construct phenotypes (mechanics only).
//
// v0.4.4.1 rename (from v0.4.4 "phenotype_low_recruitability/B/C" naming to mechanical-construct
// labels):
//
//   v0.4.4 keys           v0.4.4.1 keys
//   ---------             ------------
//   Baseline           → phenotype_baseline
//   phenotype_low_recruitability (mild)    → phenotype_low_recruitability
//   phenotype_moderate_recruitability (moderate)→ phenotype_moderate_recruitability
//   phenotype_high_recruitability (severe)  → phenotype_high_recruitability
//
// The mechanical parameters are unchanged from v0.4.4. Only the
// externally-exposed labels changed. The labels are mechanical-construct
// descriptors (recruitable pool size), NOT clinical ARDS severity grades.
//
// v0.4.4 separation of concerns (unchanged):
//
//   Phenotype owns ONLY mechanics:
//     - compartment fractions, resistances, capacities, K
//     - perfusion/deadSpace fractions
//     - central airway resistance
//     - airway opening pressure (AOP) — this is an intrinsic tissue property,
//       NOT a ventilator setting, so it stays on the phenotype
//
//   Phenotype does NOT own:
//     - initialPEEP (ventilator scenario owns this)
//     - initialRecruitmentState (no guessed fraction; either supplied by
//       caller as initialRecruitmentState, or built from an explicit
//       initializationHistory)
//
// The dynamic engine (contracts.js makeInitialState) requires the caller
// to supply either initialRecruitmentState or initializationHistory.
// If neither is given, the call fails explicitly rather than guessing.

const C0 = 0.120;
const K_NORMAL = 30;
const K_RECRUITABLE = 22;
const K_CONSOLIDATED = 35;

function makeCompartment({ id, fraction, resistance, perfusion, deadSpace,
                           elasticScale = K_NORMAL }) {
  const c = fraction * C0;        // L/cmH2O effective spring stiffness
  return {
    id, fraction,
    resistance,
    capacity: c * elasticScale,    // saturation asymptote L
    elasticScale,
    perfusionFraction: perfusion,
    deadSpaceFraction: deadSpace,
  };
}

function presetBaseline() {
  return {
    // Baseline: healthy lung, no recruitable pool, normal AOP=0.
    compartments: [
      makeCompartment({ id: 'normal', fraction: 0.98, resistance: 0.5,
                       perfusion: 0.98, deadSpace: 0.30,
                       elasticScale: K_NORMAL }),
      makeCompartment({ id: 'recruitable', fraction: 0.00, resistance: 0.5,
                       perfusion: 0.00, deadSpace: 0.30,
                       elasticScale: K_RECRUITABLE }),
      makeCompartment({ id: 'consolidated', fraction: 0.02, resistance: 0.5,
                       perfusion: 0.02, deadSpace: 0.30,
                       elasticScale: K_CONSOLIDATED }),
    ],
    centralAirwayResistance: 2.5,
    airwayOpeningPressure: 0,
  };
}

function presetPhenotypeLowRecruitability() {
  // Mechanical construct: small recruitable pool (25%), modest AOP shift.
  return {
    compartments: [
      makeCompartment({ id: 'normal', fraction: 0.65, resistance: 0.7,
                       perfusion: 0.75, deadSpace: 0.40,
                       elasticScale: K_NORMAL }),
      makeCompartment({ id: 'recruitable', fraction: 0.25, resistance: 0.5,
                       perfusion: 0.18, deadSpace: 0.40,
                       elasticScale: K_RECRUITABLE }),
      makeCompartment({ id: 'consolidated', fraction: 0.10, resistance: 0.5,
                       perfusion: 0.07, deadSpace: 0.40,
                       elasticScale: K_CONSOLIDATED }),
    ],
    centralAirwayResistance: 3.0,
    airwayOpeningPressure: 2,
  };
}

function presetPhenotypeModerateRecruitability() {
  // Mechanical construct: 40% recruitable pool, AOP=4.
  return {
    compartments: [
      makeCompartment({ id: 'normal', fraction: 0.40, resistance: 0.8,
                       perfusion: 0.55, deadSpace: 0.50,
                       elasticScale: K_NORMAL }),
      makeCompartment({ id: 'recruitable', fraction: 0.40, resistance: 0.5,
                       perfusion: 0.30, deadSpace: 0.50,
                       elasticScale: K_RECRUITABLE }),
      makeCompartment({ id: 'consolidated', fraction: 0.20, resistance: 0.5,
                       perfusion: 0.15, deadSpace: 0.50,
                       elasticScale: K_CONSOLIDATED }),
    ],
    centralAirwayResistance: 3.5,
    airwayOpeningPressure: 4,
  };
}

function presetPhenotypeHighRecruitability() {
  // Mechanical construct: 50% recruitable pool, AOP=6.
  return {
    compartments: [
      makeCompartment({ id: 'normal', fraction: 0.20, resistance: 1.0,
                       perfusion: 0.30, deadSpace: 0.60,
                       elasticScale: K_NORMAL }),
      makeCompartment({ id: 'recruitable', fraction: 0.50, resistance: 0.5,
                       perfusion: 0.45, deadSpace: 0.60,
                       elasticScale: K_RECRUITABLE }),
      makeCompartment({ id: 'consolidated', fraction: 0.30, resistance: 0.5,
                       perfusion: 0.25, deadSpace: 0.60,
                       elasticScale: K_CONSOLIDATED }),
    ],
    centralAirwayResistance: 5.0,
    airwayOpeningPressure: 6,
  };
}

const PRESETS = Object.freeze({
  phenotype_baseline: presetBaseline,
  phenotype_low_recruitability: presetPhenotypeLowRecruitability,
  phenotype_moderate_recruitability: presetPhenotypeModerateRecruitability,
  phenotype_high_recruitability: presetPhenotypeHighRecruitability,
});

module.exports = { PRESETS };

},
"src/scenario.js":function(module,exports,require){
// UI scenario contract. Mechanics-only: no oxygenation claims or controls.
const { Simulation, VcAcController, PcAcController } = require("src/simulation.js");
const { PRESETS } = require("src/presets.js");
const { makePatientParams } = require("src/contracts.js");
const VERSION = '0.4.5';
function validateScenario(s) {
  if (!s || !Object.hasOwn(PRESETS, s.preset)) throw new Error('Choose a listed mechanical phenotype.');
  if (!['VC', 'PC'].includes(s.mode)) throw new Error('Choose volume or pressure control.');
  const ranges = { peep: [0, 20], rr: [6, 40], breaths: [2, 10], dt: [0.0005, 0.005], recruitment: [0, 1] };
  if (s.mode === 'VC') Object.assign(ranges, { vt: [0.1, 1], flow: [0.1, 2], pause: [0, 2] });
  else Object.assign(ranges, { pinsp: [1, 40], ti: [0.2, 3] });
  for (const [key, [lo, hi]] of Object.entries(ranges)) {
    if (!Number.isFinite(s[key]) || s[key] < lo || s[key] > hi) throw new Error(`${key} must be between ${lo} and ${hi}.`);
  }
  if (!Number.isInteger(s.breaths)) throw new Error('Number of breaths must be a whole number.');
  const inspiration = s.mode === 'VC' ? s.vt / s.flow + s.pause : s.ti;
  if (inspiration >= 60 / s.rr) throw new Error('Inspiration is too long. Reduce tidal volume, pause, or rate; or increase inspiratory flow.');
  return s;
}
function createScenario(input) {
  const s = validateScenario(input);
  const params = makePatientParams(PRESETS[s.preset]());
  const controller = s.mode === 'VC'
    ? new VcAcController({ peep: s.peep, rr: s.rr, fio2: 0.4, vt: s.vt, inspiratoryFlow: s.flow, inspiratoryPause: s.pause })
    : new PcAcController({ peep: s.peep, rr: s.rr, fio2: 0.4, pinsp: s.pinsp, inspiratoryTime: s.ti, inspiratoryPause: 0 });
  // Normal tissue open, consolidated tissue closed. Recruitable fraction is
  // explicit and visible to the learner; reference has no recruitable pool.
  const recruitment = params.compartments.find(c => c.id === 'recruitable').fraction > 0 ? s.recruitment : 0;
  const sim = new Simulation({ params, controller, dt: s.dt, trackGas: false,
    initialPEEP: s.peep, initialRecruitmentState: { normal: 1, recruitable: recruitment, consolidated: 0 } });
  return { sim, duration: s.breaths * 60 / s.rr };
}
function summarize(sim, scenario) {
  const metrics = sim.metrics().filter(m => m.Ti > 0 && m.Te > 0).at(-1);
  if (!metrics) throw new Error('No complete breath available. Increase the number of breaths.');
  const trace = sim.trace;
  const stride = Math.max(1, Math.ceil(trace.length / 1200));
  const waveform = trace.filter((_, i) => i % stride === 0 || i === trace.length - 1).map(r => ({
    t: r.t, pressure: r.output.airwayPressure, flow: r.output.airwayFlow, volume: r.output.totalVolume * 1000,
  }));
  const stats = { steps: trace.length, newtonIterations: 0, substeps: 0, activeSetTransitions: 0, failures: 0 };
  for (const r of trace) {
    const s = r.output.solverStats || {};
    stats.newtonIterations += s.newtonIters || 0;
    stats.substeps += s.substeps || 0;
    stats.activeSetTransitions += s.activeSetTransitions || 0;
  }
  // Do not present a dynamic pressure as a measured plateau.
  const pauseRows = trace.filter(r => r.t >= metrics.breathStartT && r.t <= metrics.breathEndT && r.phase === 'PAUSE');
  const late = pauseRows.slice(Math.floor(pauseRows.length / 2));
  const plateauAvailable = scenario.mode === 'VC' && scenario.pause >= 0.1 && late.length > 0 && late.every(r =>
    Math.abs(r.output.airwayFlow) < 0.01 && (r.output.compartmentFlows || []).every(q => Math.abs(q) < 0.01));
  const shown = { ...metrics, Pplat: plateauAvailable ? metrics.Pplat : null, drivingPressure: plateauAvailable ? metrics.drivingPressure : null };
  return { version: VERSION, scenario: { ...scenario }, metrics: shown, waveform, stats,
    compartments: sim.state.compartments.map(c => ({ id: c.id, recruitment: c.recruitment, volume: c.volume, pressure: c.alveolarPressure })),
    plateauNote: plateauAvailable ? 'Plateau estimated during the late, low-flow inspiratory pause.' : 'Plateau and driving pressure require a settled, low-flow VC inspiratory pause; unavailable for this run.',
    scope: 'Educational mechanical model. No gas exchange or patient-specific validation.' };
}
function runScenario(s, progress = () => {}) {
  const { sim, duration } = createScenario(s);
  const limit = Math.ceil(duration / s.dt) + 2;
  let count = 0;
  while (sim.state.t < duration) {
    if (++count > limit) throw new Error('Simulation stopped: time did not advance.');
    const result = sim.step();
    if (result.failed) {
      const error = new Error(`Run stopped at ${sim.state.t.toFixed(3)} s: ${result.output.failureKind || 'STEP_FAILED'}. Try a smaller timestep or revise the scenario.`);
      error.diagnostics = result.output;
      throw error;
    }
    if (count % 1000 === 0) progress(Math.min(99, Math.floor(100 * sim.state.t / duration)));
  }
  return summarize(sim, s);
}
module.exports = { VERSION, validateScenario, createScenario, summarize, runScenario };

}};
const cache={};
function require(id){if(cache[id])return cache[id].exports;const m=cache[id]={exports:{}};modules[id](m,m.exports,require);return m.exports;}
return require('src/browser-entry.js');
})();
