// Dependency-free CommonJS bundler for this project's local, static requires.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const modules = new Map();
function collect(id) {
  if (modules.has(id)) return;
  let source = fs.readFileSync(path.join(root, id), 'utf8');
  modules.set(id, '');
  source = source.replace(/require\(['"]([^'"]+)['"]\)/g, (_, dependency) => {
    if (!dependency.startsWith('.')) throw new Error(`External dependency: ${dependency}`);
    const target = path.posix.normalize(path.posix.join(path.posix.dirname(id), dependency));
    if (!target.startsWith('src/') || !target.endsWith('.js')) throw new Error(`Unexpected module: ${target}`);
    collect(target);
    return `require(${JSON.stringify(target)})`;
  });
  modules.set(id, source);
}
collect('src/browser-entry.js');
const entries = [...modules].map(([id, source]) => `${JSON.stringify(id)}:function(module,exports,require){\n${source}\n}`).join(',\n');
const bundle = `/* Generated by npm run build. Version 0.4.5. */\n'use strict';\nvar VENT = (() => {\nconst modules={${entries}};\nconst cache={};\nfunction require(id){if(cache[id])return cache[id].exports;const m=cache[id]={exports:{}};modules[id](m,m.exports,require);return m.exports;}\nreturn require('src/browser-entry.js');\n})();\n`;
fs.writeFileSync(path.join(root, 'web/engine.js'), bundle);
console.log(`Built web/engine.js from ${modules.size} source modules.`);
